import type { Topic } from '../types'
import { Terminal } from 'lucide-react'

export const topic103: Topic = {
    id: '103',
    title: 'GNU and Unix Commands',
    icon: Terminal,
    description:
      'Master the command line: text processing, file management, pipes, processes, priorities, regular expressions, and the vi editor.',
    lessons: [
      {
        id: '103.1',
        topicId: '103',
        title: 'Work on the Command Line',
        weight: 4,
        description:
          'Interact with the shell. Use environment variables, command history, quoting, and identify command types.',
        sections: [
          {
            type: 'h2',
            text: 'Bash Basics',
          },
          {
            type: 'p',
            text: 'bash (Bourne Again SHell) is the default shell on most Linux systems. It reads commands interactively or from scripts.',
          },
          {
            type: 'table',
            headers: ['Concept', 'Description'],
            rows: [
              ['PATH', 'Colon-separated list of directories searched for commands'],
              ['HOME', 'Current user\'s home directory'],
              ['USER / LOGNAME', 'Username of the current user'],
              ['SHELL', 'Path to the current shell'],
              ['PS1', 'Primary prompt string'],
              ['PWD', 'Current working directory'],
              ['OLDPWD', 'Previous working directory'],
              ['$?', 'Exit status of last command (0 = success)'],
              ['$$', 'PID of current shell process'],
              ['$!', 'PID of last background process'],
            ],
          },
          {
            type: 'h2',
            text: 'Environment Variables',
          },
          {
            type: 'code',
            text: '# View all environment variables\nenv\nprintenv\n\n# View one variable\necho $HOME\nprintenv HOME\n\n# Set a variable (shell-local)\nMYVAR="hello"\n\n# Export to environment (visible to child processes)\nexport MYVAR="hello"\nexport PATH="$PATH:/opt/myapp/bin"\n\n# Unset a variable\nunset MYVAR\n\n# Run command with temporary env\nMYVAR=test ./myscript',
          },
          {
            type: 'h2',
            text: 'Command History',
          },
          {
            type: 'table',
            headers: ['Command/Syntax', 'Description'],
            rows: [
              ['history', 'Show command history list'],
              ['history N', 'Show last N commands'],
              ['!N', 'Re-run command number N'],
              ['!!', 'Re-run last command'],
              ['!string', 'Re-run last command starting with string'],
              ['!?string', 'Re-run last command containing string'],
              ['Ctrl+R', 'Reverse search through history'],
              ['HISTSIZE', 'Number of commands kept in memory'],
              ['HISTFILE', 'File to save history (~/.bash_history)'],
              ['HISTFILESIZE', 'Lines stored in HISTFILE'],
            ],
          },
          {
            type: 'h2',
            text: 'Command Types and Identification',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['type <cmd>', 'Identify what type a command is (alias, builtin, function, file)'],
              ['which <cmd>', 'Find the first executable in PATH'],
              ['whereis <cmd>', 'Find binary, source, and man page locations'],
              ['whatis <cmd>', 'One-line description from man page'],
              ['man <cmd>', 'Display manual page'],
            ],
          },
          {
            type: 'code',
            text: '# type differentiates between builtins, aliases, and executables\ntype cd        # cd is a shell builtin\ntype ls        # ls is aliased to `ls --color=auto`\ntype /bin/ls   # /bin/ls is /bin/ls\n\n# Source a file into current shell (execute in current context)\nsource ~/.bashrc\n. ~/.bashrc       # Same thing (dot command)',
          },
          {
            type: 'h2',
            text: 'Quoting',
          },
          {
            type: 'table',
            headers: ['Quote Type', 'Effect'],
            rows: [
              ['"double quotes"', 'Expands variables ($VAR) and command substitution ($(cmd)) but NOT glob characters'],
              ["'single quotes'", 'Preserves everything literally — no expansion at all'],
              ['\\backslash', 'Escapes the next single character'],
              ['$(cmd) or `cmd`', 'Command substitution — replaces with command output'],
            ],
          },
          {
            type: 'h2',
            text: 'Shell Configuration Files',
          },
          {
            type: 'p',
            text: 'Bash reads different configuration files depending on whether it is a login shell or an interactive non-login shell.',
          },
          {
            type: 'table',
            headers: ['File', 'When Read', 'Purpose'],
            rows: [
              ['/etc/profile', 'Login shell, system-wide', 'Global environment variables, PATH'],
              ['/etc/profile.d/*.sh', 'Login shell (sourced by /etc/profile)', 'Modular system-wide settings'],
              ['~/.bash_profile', 'Login shell, user', 'User-specific login config; usually sources ~/.bashrc'],
              ['~/.bash_login', 'Login shell, user (if .bash_profile missing)', 'Alternative to .bash_profile'],
              ['~/.profile', 'Login shell, user (if .bash_profile and .bash_login missing)', 'POSIX-compatible; works with sh too'],
              ['~/.bashrc', 'Interactive non-login shell', 'Aliases, functions, prompt, interactive settings'],
              ['~/.bash_logout', 'Logout from login shell', 'Cleanup commands on logout'],
              ['/etc/bash.bashrc', 'Interactive non-login shell, system-wide', 'System-wide interactive settings (Debian)'],
            ],
          },
          {
            type: 'tip',
            title: 'Login vs Non-Login Shell',
            body: 'A login shell is started when you log in via console, SSH, or su -. A non-login shell is a terminal window inside a GUI, or a subshell. ~/.bash_profile reads on login; ~/.bashrc reads on every interactive shell. Best practice: put settings in ~/.bashrc and source it from ~/.bash_profile.',
          },
          {
            type: 'code',
            text: '# Check if current shell is a login shell\necho $0\n# Login shell: output is  -bash  (leading dash)\n# Non-login: output is  bash\n\n# Source bashrc manually\nsource ~/.bashrc\n. ~/.bashrc   # identical\n\n# Add to PATH permanently in ~/.bashrc\nexport PATH="$PATH:/opt/myapp/bin"\n\n# Create an alias in ~/.bashrc\nalias ll=\'ls -alF\'\nalias grep=\'grep --color=auto\'',
          },
          {
            type: 'h2',
            text: 'man Pages — The Manual System',
          },
          {
            type: 'p',
            text: 'man (manual) pages are the primary Linux documentation system. Each command, system call, config file, etc. has a manual page.',
          },
          {
            type: 'table',
            headers: ['Section', 'Content'],
            rows: [
              ['1', 'User commands (ls, cp, grep, ...)'],
              ['2', 'System calls (open, write, fork, ...)'],
              ['3', 'Library functions (printf, malloc, ...)'],
              ['4', 'Special device files (/dev/null, ...)'],
              ['5', 'File formats and conventions (/etc/passwd, fstab, ...)'],
              ['6', 'Games and screensavers'],
              ['7', 'Miscellaneous (signal, locale, regex, ...)'],
              ['8', 'System administration commands (mount, fdisk, ...)'],
              ['9', 'Kernel routines (documentation for kernel developers)'],
            ],
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['man ls', 'Show man page for ls (section 1)'],
              ['man 5 passwd', 'Show man page for passwd in section 5 (file format)'],
              ['man -k keyword', 'Search man page descriptions (same as apropos)'],
              ['apropos keyword', 'Search descriptions for keyword'],
              ['whatis ls', 'One-line description of ls'],
              ['man -f ls', 'Same as whatis ls'],
              ['info ls', 'Display info page (GNU info system, more detailed)'],
              ['ls --help', 'Quick built-in help for most GNU commands'],
            ],
          },
          {
            type: 'h2',
            text: 'Bash Keyboard Shortcuts',
          },
          {
            type: 'table',
            headers: ['Shortcut', 'Action'],
            rows: [
              ['Ctrl+C', 'Interrupt (SIGINT) foreground process'],
              ['Ctrl+Z', 'Suspend foreground process (SIGTSTP)'],
              ['Ctrl+D', 'Send EOF / logout from shell'],
              ['Ctrl+L', 'Clear the screen (like clear command)'],
              ['Ctrl+A', 'Move cursor to beginning of line'],
              ['Ctrl+E', 'Move cursor to end of line'],
              ['Ctrl+U', 'Delete from cursor to start of line'],
              ['Ctrl+K', 'Delete from cursor to end of line'],
              ['Ctrl+W', 'Delete the word before cursor'],
              ['Ctrl+R', 'Reverse search through history'],
              ['Tab', 'Auto-complete command, file, or directory'],
              ['Tab Tab', 'Show all completion possibilities'],
            ],
          },
          {
            type: 'h2',
            text: 'Aliases',
          },
          {
            type: 'code',
            text: '# Create an alias\nalias ll="ls -alF"\nalias grep="grep --color=auto"\nalias rm="rm -i"            # make rm interactive\n\n# List all aliases\nalias\n\n# Remove an alias\nunalias ll\n\n# Alias with arguments - use a function instead:\ngreet() { echo "Hello, $1"; }\n\n# Make aliases permanent: add to ~/.bashrc\n# Aliases are NOT inherited by subshells or scripts (only interactive shells)',
          },
          {
            type: 'h2',
            text: 'Shell Variables — set and unset',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['set', 'Display all shell variables AND functions'],
              ['set -x', 'Debug mode: print each command before executing'],
              ['set +x', 'Turn off debug mode'],
              ['set -e', 'Exit immediately if a command fails'],
              ['set -u', 'Treat unset variables as errors'],
              ['env', 'Display exported (environment) variables only'],
              ['export VAR=val', 'Set and export variable to child processes'],
              ['export -n VAR', 'Un-export variable (keep as shell variable)'],
              ['unset VAR', 'Remove a variable entirely'],
              ['readonly VAR=val', 'Set a variable that cannot be changed'],
            ],
          },
          {
            type: 'h2',
            text: 'Special Variables',
          },
          {
            type: 'table',
            headers: ['Variable', 'Meaning'],
            rows: [
              ['$0', 'Name of the current script or shell'],
              ['$1 - $9', 'Positional parameters (script arguments)'],
              ['$#', 'Number of positional parameters'],
              ['$*', 'All positional parameters as a single word'],
              ['$@', 'All positional parameters as separate words (preserves quoting)'],
              ['$?', 'Exit status of last command (0=success, non-zero=error)'],
              ['$$', 'PID of current shell'],
              ['$!', 'PID of last background job'],
              ['$-', 'Current shell option flags'],
              ['$_', 'Last argument of previous command'],
            ],
          },
          {
            type: 'h2',
            text: 'Advanced Globbing',
          },
          {
            type: 'table',
            headers: ['Pattern', 'Matches'],
            rows: [
              ['*', 'Any string (including empty), NOT hidden files (no leading dot)'],
              ['.*', 'Hidden files (starting with dot)'],
              ['?', 'Any single character'],
              ['[abc]', 'One of: a, b, or c'],
              ['[!abc]', 'Any character NOT a, b, or c'],
              ['[0-9]', 'Any single digit'],
              ['{jpg,png,gif}', 'Brace expansion: exactly these strings'],
              ['{1..5}', 'Sequence expansion: 1 2 3 4 5'],
              ['~', 'HOME directory of current user'],
              ['~alice', 'HOME directory of user alice'],
            ],
          },
          {
            type: 'exam',
            title: 'Exam Tips',
            body: 'Know the difference between single and double quotes. Know that source / dot (.) executes in current shell context (not a subshell). Know type, which, whereis. Know $?, $$, $!, $#, $@, $*. HISTSIZE controls memory history; HISTFILESIZE controls disk history. Login shell reads ~/.bash_profile; interactive shell reads ~/.bashrc. man -k and apropos search man page descriptions. man section 5 = file formats; section 8 = admin commands. alias creates shortcuts; aliases are NOT exported to subshells. set shows all shell variables and functions; env shows only exported variables.',
          },
        ],
      },
      {
        id: '103.2',
        topicId: '103',
        title: 'Process Text Streams Using Filters',
        weight: 2,
        description:
          'Use standard text processing tools to filter and transform text: cat, grep, cut, sort, uniq, head, tail, wc, sed, tr, and more.',
        sections: [
          {
            type: 'h2',
            text: 'Essential Text Processing Commands',
          },
          {
            type: 'table',
            headers: ['Command', 'Purpose', 'Key Options'],
            rows: [
              ['cat', 'Concatenate and display files', '-n (line numbers), -A (show non-printing)'],
              ['head', 'Show first N lines (default 10)', '-n N'],
              ['tail', 'Show last N lines (default 10)', '-n N, -f (follow/watch)'],
              ['wc', 'Count lines/words/bytes', '-l (lines), -w (words), -c (bytes), -m (chars)'],
              ['sort', 'Sort lines', '-n (numeric), -r (reverse), -k N (key field), -u (unique), -f (case-insensitive)'],
              ['uniq', 'Remove/report adjacent duplicate lines', '-c (count), -d (only duplicates), -u (only unique)'],
              ['cut', 'Extract columns/fields', '-d DELIM (delimiter), -f N (field N), -c N-M (chars)'],
              ['tr', 'Translate or delete characters', '-d (delete), -s (squeeze), tr a-z A-Z'],
              ['paste', 'Merge lines of files side-by-side', '-d DELIM'],
              ['join', 'Join lines of two files on a common field', '-1 N -2 N'],
              ['expand', 'Convert tabs to spaces', '-t N'],
              ['nl', 'Number lines', '-v N (start number)'],
              ['od', 'Dump file in octal/hex/char', '-c (chars), -x (hex)'],
              ['fmt', 'Reformat paragraphs', '-w N (width)'],
              ['pr', 'Format file for printing', '-h (header), -n (line numbers)'],
              ['split', 'Split file into pieces', '-l N (lines), -b N (bytes)'],
            ],
          },
          {
            type: 'h2',
            text: 'grep — Search Text',
          },
          {
            type: 'table',
            headers: ['Option', 'Description'],
            rows: [
              ['-i', 'Case-insensitive match'],
              ['-v', 'Invert match (show non-matching lines)'],
              ['-c', 'Count matching lines'],
              ['-n', 'Show line numbers'],
              ['-r / -R', 'Recursive directory search'],
              ['-l', 'List filenames only (not matching lines)'],
              ['-E', 'Extended regex (same as egrep)'],
              ['-F', 'Fixed strings (no regex, same as fgrep)'],
              ['-A N', 'Show N lines After match'],
              ['-B N', 'Show N lines Before match'],
              ['-o', 'Print only the matching part'],
            ],
          },
          {
            type: 'h2',
            text: 'sed — Stream Editor',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['sed \'s/old/new/\' file', 'Replace first occurrence per line'],
              ['sed \'s/old/new/g\' file', 'Replace all occurrences (global)'],
              ['sed \'s/old/new/gi\' file', 'Replace all, case-insensitive'],
              ['sed -n \'5,10p\' file', 'Print lines 5–10 only (-n suppresses default print)'],
              ['sed \'5,10d\' file', 'Delete lines 5–10'],
              ['sed -i \'s/old/new/g\' file', 'Edit file in-place'],
              ['sed \'/^#/d\' file', 'Delete comment lines starting with #'],
              ['sed -n \'/pattern/p\' file', 'Print only lines matching pattern'],
              ['sed \'$d\' file', 'Delete last line'],
              ['sed \'s/^/  /\' file', 'Indent every line by 2 spaces'],
            ],
          },
          {
            type: 'h2',
            text: 'awk — Pattern Scanning and Processing',
          },
          {
            type: 'p',
            text: 'awk is a powerful text processing language. It processes files line by line, splitting each line into fields (default delimiter: whitespace).',
          },
          {
            type: 'table',
            headers: ['awk Command', 'Description'],
            rows: [
              ['awk \'{print $1}\' file', 'Print first field of each line'],
              ['awk \'{print $1, $3}\' file', 'Print fields 1 and 3'],
              ['awk -F: \'{print $1}\' /etc/passwd', 'Use colon as field separator'],
              ['awk \'NR==3\' file', 'Print only line 3 (NR = record number)'],
              ['awk \'NR>=2 && NR<=5\' file', 'Print lines 2–5'],
              ['awk \'$3 > 100\' file', 'Print lines where field 3 > 100'],
              ['awk \'/pattern/ {print $0}\' file', 'Print lines matching pattern'],
              ['awk \'END {print NR}\' file', 'Count total lines (like wc -l)'],
              ['awk \'{sum += $1} END {print sum}\' file', 'Sum values in field 1'],
              ['awk -F: \'{print $1 ":" $3}\' /etc/passwd', 'Print username:UID'],
            ],
          },
          {
            type: 'h2',
            text: 'tr — Translate Characters',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['tr a-z A-Z < file', 'Convert lowercase to uppercase'],
              ['tr -d \'\\n\' < file', 'Remove all newlines'],
              ['tr -d \'[0-9]\' < file', 'Remove all digits'],
              ['tr -s \' \' < file', 'Squeeze consecutive spaces into one'],
              ['tr \'[\\t]\' \' \' < file', 'Replace tabs with spaces'],
              ['tr -dc \'[:print:]\' < file', 'Delete non-printable characters'],
            ],
          },
          {
            type: 'code',
            text: '# Count users in /etc/passwd\nwc -l /etc/passwd\n\n# Extract usernames (field 1, colon-separated)\ncut -d: -f1 /etc/passwd | sort\n\n# Using awk to get username and UID\nawk -F: \'{print $1, $3}\' /etc/passwd\n\n# Find 5 most common words\ncat file.txt | tr -s \'[:space:]\' \'\\n\' | sort | uniq -c | sort -rn | head -5\n\n# Show unique IPs from an access log\ncut -d\' \' -f1 /var/log/nginx/access.log | sort -u\n\n# Replace all tabs with spaces\nexpand -t 4 code.py\n\n# Follow a log file in real time\ntail -f /var/log/syslog\n\n# Count lines/words/bytes in a file\nwc -lwc /etc/passwd\n\n# Split a 100MB file into 10MB chunks\nsplit -b 10M bigfile.tar.gz part_\n# Creates: part_aa, part_ab, part_ac ...\n# Reassemble:\ncat part_* > bigfile.tar.gz\n\n# paste: merge two files side by side\npaste file1.txt file2.txt\npaste -d: file1.txt file2.txt\n\n# od: dump binary/non-printable file content\nod -c /bin/ls | head\nod -x file | head   # hexadecimal dump',
          },
          {
            type: 'exam',
            title: 'Exam Tips',
            body: 'sort -u is same as sort | uniq. uniq only removes consecutive duplicates — sort first! cut -d: -f1 extracts field 1. awk -F: uses colon as separator; $1, $2 are fields; NR is the line number. sed -n suppresses default output; -i edits in-place. tail -f follows growing files. grep -v inverts match. tr converts characters; -d deletes; -s squeezes.',
          },
        ],
      },
      {
        id: '103.3',
        topicId: '103',
        title: 'Perform Basic File Management',
        weight: 4,
        description:
          'Create, delete, copy, move files and directories. Use wildcards, tar, and file compression tools.',
        sections: [
          {
            type: 'h2',
            text: 'File Operations',
          },
          {
            type: 'table',
            headers: ['Command', 'Description', 'Key Options'],
            rows: [
              ['ls', 'List directory contents', '-l (long), -a (hidden), -h (human sizes), -R (recursive), -i (inode)'],
              ['cp', 'Copy files/directories', '-r (recursive dirs), -p (preserve perms/time), -i (interactive), -v (verbose)'],
              ['mv', 'Move/rename files', '-i (interactive), -v (verbose)'],
              ['rm', 'Remove files', '-r (recursive), -f (force, no prompt), -i (interactive)'],
              ['mkdir', 'Create directory', '-p (create parent dirs)'],
              ['rmdir', 'Remove empty directory', '-p (remove parents too)'],
              ['touch', 'Create empty file or update timestamps', '-t YYMMDDHHMM'],
              ['file', 'Determine file type', ''],
              ['find', 'Search for files (see below)', ''],
            ],
          },
          {
            type: 'h2',
            text: 'Wildcards (Globbing)',
          },
          {
            type: 'table',
            headers: ['Pattern', 'Matches'],
            rows: [
              ['*', 'Any string (including empty)'],
              ['?', 'Any single character'],
              ['[abc]', 'Any one of: a, b, or c'],
              ['[a-z]', 'Any character in range a–z'],
              ['[!abc]', 'Any character NOT a, b, or c'],
              ['{a,b,c}', 'Brace expansion: literally a, b, or c'],
            ],
          },
          {
            type: 'h2',
            text: 'find — Search Files',
          },
          {
            type: 'code',
            text: '# Find by name\nfind /home -name "*.txt"\nfind /home -iname "*.txt"         # case-insensitive\n\n# Find by type\nfind /tmp -type f                  # files only\nfind /tmp -type d                  # directories only\nfind /tmp -type l                  # symbolic links\n\n# Find by size\nfind / -size +100M                 # larger than 100 MB\nfind / -size -10k                  # smaller than 10 KB\n\n# Find by modification time\nfind / -mtime -7                   # modified in last 7 days\nfind / -mmin -60                   # modified in last 60 minutes\n\n# Find by permissions\nfind / -perm 644                   # exact permissions\nfind / -perm /u+s                  # SUID bit set\n\n# Find by owner and execute action\nfind /tmp -user john -exec rm {} \\;\nfind /tmp -user john -exec rm {} +    # Faster: batches arguments',
          },
          {
            type: 'h2',
            text: 'Archiving and Compression',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['tar -cvf archive.tar dir/', 'Create tar archive (v=verbose)'],
              ['tar -xvf archive.tar', 'Extract tar archive'],
              ['tar -tvf archive.tar', 'List contents of archive'],
              ['tar -czvf archive.tar.gz dir/', 'Create gzip-compressed archive'],
              ['tar -xzvf archive.tar.gz', 'Extract gzip-compressed archive'],
              ['tar -cjvf archive.tar.bz2 dir/', 'Create bzip2-compressed archive'],
              ['tar -cJvf archive.tar.xz dir/', 'Create xz-compressed archive'],
              ['tar -czvf archive.tar.gz -C /path dir/', '-C: change to directory before archiving'],
              ['gzip file', 'Compress file → file.gz (removes original)'],
              ['gunzip file.gz', 'Decompress gzip file'],
              ['bzip2 file', 'Compress file → file.bz2 (better ratio than gzip)'],
              ['bunzip2 file.bz2', 'Decompress bzip2 file'],
              ['xz file', 'Compress file → file.xz (best ratio)'],
              ['unxz file.xz', 'Decompress xz file'],
              ['zip archive.zip files', 'Create ZIP archive'],
              ['unzip archive.zip', 'Extract ZIP archive'],
            ],
          },
          {
            type: 'h2',
            text: 'dd — Low-Level Copy',
          },
          {
            type: 'code',
            text: '# Backup entire disk to image\ndd if=/dev/sda of=/backup/sda.img bs=4M\n\n# Restore disk from image\ndd if=/backup/sda.img of=/dev/sda bs=4M\n\n# Create a swap file\ndd if=/dev/zero of=/swapfile bs=1M count=2048\n\n# Wipe a partition\ndd if=/dev/urandom of=/dev/sdb1 bs=4M\n\n# Monitor dd progress\ndd if=/dev/sda of=/dev/sdb bs=4M status=progress\n\n# Key options: if=input, of=output, bs=block size, count=number of blocks, skip=skip input blocks, seek=skip output blocks',
          },
          {
            type: 'h2',
            text: 'cpio — Copy Input/Output Archive',
          },
          {
            type: 'p',
            text: 'cpio creates and extracts archives. It is used for initramfs archives and is an alternative to tar.',
          },
          {
            type: 'code',
            text: '# Create cpio archive from find output\nfind . -name "*.conf" | cpio -ov > configs.cpio\n\n# Extract cpio archive\ncpio -idv < configs.cpio\n\n# List contents of cpio archive\ncpio -t < archive.cpio\n\n# Options: -o=create, -i=extract, -t=list, -v=verbose, -d=create dirs, -p=pass-through',
          },
          {
            type: 'h2',
            text: 'File Timestamps',
          },
          {
            type: 'table',
            headers: ['Timestamp', 'Command to view', 'Description'],
            rows: [
              ['mtime (modification time)', 'ls -l, stat', 'When file contents were last modified'],
              ['atime (access time)', 'ls -lu, stat', 'When file was last read/accessed'],
              ['ctime (change time)', 'ls -lc, stat', 'When file metadata (permissions, owner) was last changed'],
            ],
          },
          {
            type: 'code',
            text: '# Show all timestamps for a file\nstat filename\n\n# touch with specific timestamp\ntouch -t 202603061200 filename    # YYYYMMDDhhmm\ntouch -d "2026-03-01 10:00:00" filename\n\n# Set atime and mtime from reference file\ntouch -r reference.file target.file',
          },
          {
            type: 'h2',
            text: 'Viewing Compressed Files Without Extracting',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['zcat file.gz', 'Print gzip file to stdout (like cat)'],
              ['zless file.gz', 'Page through gzip file (like less)'],
              ['zgrep pattern file.gz', 'Search inside gzip file'],
              ['zdiff file1.gz file2.gz', 'Diff two gzip files'],
              ['bzcat file.bz2', 'Print bzip2 file to stdout'],
              ['bzless file.bz2', 'Page through bzip2 file'],
              ['bzgrep pattern file.bz2', 'Search inside bzip2 file'],
              ['xzcat file.xz', 'Print xz file to stdout'],
              ['xzless file.xz', 'Page through xz file'],
              ['gzip -k file', 'Compress but KEEP original (default removes it)'],
              ['gzip -d file.gz', 'Decompress (same as gunzip)'],
              ['gzip -l file.gz', 'List compression info and ratio'],
              ['gzip -1 / -9', 'Fastest / best compression'],
            ],
          },
          {
            type: 'h2',
            text: 'tar — Advanced Options',
          },
          {
            type: 'code',
            text: '# Exclude files from archive\ntar -czvf backup.tar.gz /home/ --exclude="/home/*/.cache"\ntar -czvf backup.tar.gz /home/ --exclude="*.mp4"\n\n# Preserve permissions and ownership\ntar -czvf backup.tar.gz -p /home/\n\n# Extract to specific directory\ntar -xzvf archive.tar.gz -C /tmp/restore/\n\n# Archive across SSH (no temp file)\ntar -czf - /home/ | ssh user@host "tar -xzf - -C /backup/"\n\n# Append to existing uncompressed archive\ntar -rvf archive.tar newfile.txt\n\n# List with verbose permissions\ntar -tvf archive.tar.gz',
          },
          {
            type: 'exam',
            title: 'Exam Tips',
            body: 'tar flags: -c=create, -x=extract, -t=list, -v=verbose, -f=file, -z=gzip, -j=bzip2, -J=xz, -C=change dir, -p=preserve permissions, --exclude=skip files. find -exec {} \\; runs once per file, {} + batches. cp -p preserves permissions/timestamps. touch creates empty files AND updates timestamps. Three timestamps: mtime (content), atime (access), ctime (metadata). dd: if=input, of=output, bs=block size. zcat/bzcat/xzcat view compressed files without extracting. gzip -k keeps the original file after compression.',
          },
          {
            type: 'files',
            files: ['/tmp/', '/dev/null', '/dev/zero', '/dev/urandom'],
          },
        ],
      },
      {
        id: '103.4',
        topicId: '103',
        title: 'Use Streams, Pipes and Redirects',
        weight: 4,
        description:
          'Redirect standard input/output/error; chain commands with pipes; use tee.',
        sections: [
          {
            type: 'h2',
            text: 'Standard Streams',
          },
          {
            type: 'table',
            headers: ['Stream', 'FD', 'Default'],
            rows: [
              ['stdin (standard input)', '0', 'Keyboard'],
              ['stdout (standard output)', '1', 'Terminal screen'],
              ['stderr (standard error)', '2', 'Terminal screen'],
            ],
          },
          {
            type: 'h2',
            text: 'Redirection Operators',
          },
          {
            type: 'table',
            headers: ['Operator', 'Description'],
            rows: [
              ['> file', 'Redirect stdout to file (truncate)'],
              ['>> file', 'Redirect stdout to file (append)'],
              ['< file', 'Redirect stdin from file'],
              ['2> file', 'Redirect stderr to file'],
              ['2>> file', 'Append stderr to file'],
              ['&> file or >file 2>&1', 'Redirect both stdout and stderr to file'],
              ['2>&1', 'Redirect stderr to same destination as stdout'],
              ['1>&2', 'Redirect stdout to stderr'],
              ['<< EOF', 'Here-document: read stdin until EOF marker'],
              ['<<< "string"', 'Here-string: feed string as stdin'],
            ],
          },
          {
            type: 'h2',
            text: 'Pipes and tee',
          },
          {
            type: 'code',
            text: '# Pipe stdout of cmd1 to stdin of cmd2\ncmd1 | cmd2\n\n# tee: write to both file and stdout simultaneously\nls -la | tee list.txt | wc -l\n\n# Append with tee\ndmesg | tee -a boot.log | grep error\n\n# Pipe both stdout and stderr\ncmd 2>&1 | grep error\n\n# /dev/null: discard output\ncmd > /dev/null       # discard stdout\ncmd > /dev/null 2>&1  # discard both',
          },
          {
            type: 'h2',
            text: 'xargs — Build Commands from stdin',
          },
          {
            type: 'code',
            text: '# Delete all .tmp files found by find\nfind /tmp -name "*.tmp" | xargs rm\n\n# Safe version with null-separated filenames (handles spaces)\nfind /tmp -name "*.tmp" -print0 | xargs -0 rm\n\n# Pass each line as argument with -I\ncat hosts.txt | xargs -I{} ping -c1 {}\n\n# Run multiple jobs in parallel\ncat list.txt | xargs -P4 -I{} wget {}',
          },
          {
            type: 'h2',
            text: 'Named Pipes (FIFOs)',
          },
          {
            type: 'p',
            text: 'A named pipe (FIFO) is a special file that allows two unrelated processes to communicate. Unlike regular pipes, it persists on the filesystem.',
          },
          {
            type: 'code',
            text: '# Create a named pipe\nmkfifo /tmp/mypipe\n\n# Writer process (in one terminal)\necho "hello" > /tmp/mypipe\n\n# Reader process (in another terminal)\ncat /tmp/mypipe\n\n# Use case: log to file and terminal simultaneously\ntar czf - /home | tee /tmp/mypipe | sha256sum\ncat /tmp/mypipe > /backup/home.tar.gz',
          },
          {
            type: 'h2',
            text: 'Process Substitution',
          },
          {
            type: 'code',
            text: '# Process substitution: treat command output as a file\ndiff <(sort file1) <(sort file2)\n\n# Compare two command outputs without temp files\ncomm <(sort list1) <(sort list2)\n\n# Redirect output to multiple commands\ntee >(gzip > file.gz) >(sha256sum > file.sha256) > file\n\n# Useful for diff, comm, join where file arguments are needed',
          },
          {
            type: 'exam',
            title: 'Exam Tips',
            body: 'Order matters: cmd > file 2>&1 (correct). cmd 2>&1 > file is WRONG order. Know FDs: 0=stdin, 1=stdout, 2=stderr. tee splits output to both file and stdout; tee -a appends. &> redirects both stdout and stderr. Named pipes (mkfifo) are persistent; regular pipes are anonymous. /dev/null discards output; > /dev/null 2>&1 discards both streams.',
          },
        ],
      },
      {
        id: '103.5',
        topicId: '103',
        title: 'Create, Monitor and Kill Processes',
        weight: 4,
        description:
          'Run processes in foreground/background, monitor with ps and top, send signals, manage jobs.',
        sections: [
          {
            type: 'h2',
            text: 'Process Concepts',
          },
          {
            type: 'table',
            headers: ['Concept', 'Description'],
            rows: [
              ['PID', 'Process ID — unique integer assigned to each process'],
              ['PPID', 'Parent PID — who spawned this process'],
              ['UID', 'User ID of the process owner'],
              ['Zombie', 'Process has exited but parent hasn\'t read its exit status'],
              ['Orphan', 'Parent has died; adopted by init/systemd (PID 1)'],
              ['Daemon', 'Background service process, no controlling terminal'],
            ],
          },
          {
            type: 'h2',
            text: 'ps — Process Status',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['ps', 'Show processes in current terminal session'],
              ['ps aux', 'Show ALL processes in BSD style (a=all, u=user-oriented, x=no-tty)'],
              ['ps -ef', 'Show ALL processes in UNIX style'],
              ['ps -u username', 'Show processes for a specific user'],
              ['ps --forest', 'Show process tree'],
              ['ps -p PID', 'Show specific process by PID'],
              ['pstree', 'Visual process tree'],
              ['pgrep name', 'Find PID by process name (returns PID)'],
              ['pgrep -l name', 'Find PID and name'],
              ['pgrep -u user name', 'Find process by user and name'],
            ],
          },
          {
            type: 'h2',
            text: 'top and htop',
          },
          {
            type: 'p',
            text: 'top displays a real-time, sorted list of running processes and system resource usage.',
          },
          {
            type: 'table',
            headers: ['Key (in top)', 'Action'],
            rows: [
              ['q', 'Quit'],
              ['k', 'Kill a process (prompts for PID and signal)'],
              ['r', 'Renice a process'],
              ['P', 'Sort by CPU usage'],
              ['M', 'Sort by memory usage'],
              ['u', 'Filter by user'],
              ['1', 'Toggle individual CPU display'],
              ['h', 'Help'],
              ['Space', 'Refresh immediately'],
            ],
          },
          {
            type: 'h2',
            text: 'Signals',
          },
          {
            type: 'table',
            headers: ['Signal', 'Number', 'Description'],
            rows: [
              ['SIGHUP', '1', 'Hang up — often used to reload config without restart'],
              ['SIGINT', '2', 'Interrupt — same as Ctrl+C'],
              ['SIGQUIT', '3', 'Quit — Ctrl+\\, creates core dump'],
              ['SIGKILL', '9', 'Kill immediately, cannot be caught or ignored'],
              ['SIGTERM', '15', 'Terminate gracefully (default signal)'],
              ['SIGSTOP', '19', 'Pause/stop process, cannot be caught'],
              ['SIGCONT', '18', 'Continue a stopped process'],
              ['SIGTSTP', '20', 'Stop from terminal — Ctrl+Z'],
              ['SIGUSR1', '10', 'User-defined signal 1'],
              ['SIGUSR2', '12', 'User-defined signal 2'],
            ],
          },
          {
            type: 'code',
            text: '# Send signal to a process\nkill PID                      # SIGTERM (15)\nkill -9 PID                   # SIGKILL\nkill -SIGKILL PID\nkill -s SIGTERM PID\n\n# Kill by name\nkillall nginx                 # kill all processes named nginx\npkill -9 firefox              # kill by name pattern\n\n# List all signals\nkill -l',
          },
          {
            type: 'h2',
            text: 'Job Control',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['cmd &', 'Run command in background'],
              ['Ctrl+Z', 'Suspend foreground process (SIGTSTP)'],
              ['jobs', 'List current shell background/stopped jobs'],
              ['fg', 'Bring last job to foreground'],
              ['fg %N', 'Bring job N to foreground'],
              ['bg', 'Resume last stopped job in background'],
              ['bg %N', 'Resume job N in background'],
              ['nohup cmd &', 'Run command immune to SIGHUP (survives logout)'],
              ['disown %N', 'Detach job N from shell (keeps running after logout)'],
            ],
          },
          {
            type: 'h2',
            text: '/proc Filesystem — Process Information',
          },
          {
            type: 'p',
            text: 'The /proc filesystem is a virtual filesystem exposing kernel and process data. Each running process has a directory /proc/PID/ with detailed information.',
          },
          {
            type: 'table',
            headers: ['File/Dir', 'Contents'],
            rows: [
              ['/proc/PID/cmdline', 'The command used to start the process (null-separated)'],
              ['/proc/PID/status', 'Human-readable process status (Name, State, PID, PPid, Uid, Gid, VmRSS)'],
              ['/proc/PID/environ', 'Environment variables of the process (null-separated)'],
              ['/proc/PID/fd/', 'Directory: symlinks to all open file descriptors'],
              ['/proc/PID/maps', 'Memory map pages for the process'],
              ['/proc/PID/exe', 'Symlink to the executable file'],
              ['/proc/PID/cwd', 'Symlink to current working directory'],
              ['/proc/cpuinfo', 'CPU model, cores, flags'],
              ['/proc/meminfo', 'Memory usage statistics'],
              ['/proc/loadavg', 'Load averages (1/5/15 min) and runnable tasks'],
              ['/proc/uptime', 'Seconds since boot'],
              ['/proc/version', 'Kernel version string'],
            ],
          },
          {
            type: 'code',
            text: '# Read process command line\ncat /proc/1234/cmdline | tr "\\0" " "\n\n# List open file descriptors\nls -la /proc/1234/fd/\n\n# Check memory info\ncat /proc/meminfo | head -20\n\n# Read load averages\ncat /proc/loadavg\n# Output: 0.52 0.35 0.28 2/400 12345\n# Columns: 1min 5min 15min running/total lastPID',
          },
          {
            type: 'h2',
            text: 'free — Display Memory Usage',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['free', 'Show memory in kilobytes'],
              ['free -h', 'Human-readable (K/M/G)'],
              ['free -m', 'Show in megabytes'],
              ['free -g', 'Show in gigabytes'],
              ['free -s 3', 'Update every 3 seconds'],
              ['free -c 5', 'Print 5 times then exit'],
            ],
          },
          {
            type: 'code',
            text: '$ free -h\n              total        used        free      shared  buff/cache   available\nMem:           15Gi        4.2Gi       6.8Gi       512Mi       4.2Gi       10Gi\nSwap:         2.0Gi          0B       2.0Gi\n\n# "available" is more useful than "free" — includes reclaimable cache\n# buff/cache = kernel buffer/page cache (can be reclaimed)',
          },
          {
            type: 'h2',
            text: 'uptime and Load Averages',
          },
          {
            type: 'code',
            text: '$ uptime\n 14:23:01 up 3 days,  2:15,  2 users,  load average: 0.52, 0.35, 0.28\n#                                        ^1min  ^5min  ^15min\n\n# Load average = average number of runnable (R) + uninterruptible (D) processes\n# Rule of thumb: load > number_of_CPUs means system is overloaded\n# Check CPU count: nproc   or   grep -c processor /proc/cpuinfo',
          },
          {
            type: 'h2',
            text: 'watch — Repeated Command Execution',
          },
          {
            type: 'code',
            text: '# Run ps every 2 seconds\nwatch -n 2 "ps aux | grep nginx"\n\n# Highlight differences between runs\nwatch -d free -h\n\n# No title bar\nwatch -t uptime\n\n# Watch and exit when output changes\nwatch -g "ls -la /tmp"',
          },
          {
            type: 'h2',
            text: 'vmstat and iostat — System Performance',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['vmstat 2 5', 'Show virtual memory stats every 2s, 5 times'],
              ['vmstat -s', 'Show summary statistics'],
              ['vmstat -d', 'Show disk statistics'],
              ['iostat', 'Show CPU and disk I/O statistics'],
              ['iostat -x 2', 'Extended disk stats, refresh every 2s'],
              ['iostat -h', 'Human-readable output'],
            ],
          },
          {
            type: 'code',
            text: '$ vmstat 1 3\nprocs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----\n r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st\n 1  0      0 6921284 1024 4316160    0    0     2    10  256  512  5  1 93  1  0',
          },
          {
            type: 'h2',
            text: 'lsof — List Open Files',
          },
          {
            type: 'p',
            text: 'lsof (list open files) shows every file (regular files, sockets, pipes, devices) currently opened by any process. On Linux, "everything is a file".',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['lsof', 'List all open files (very verbose)'],
              ['lsof /var/log', 'List processes with files open in /var/log'],
              ['lsof /dev/sda1', 'List processes using a device (helps with "device busy")'],
              ['lsof -p PID', 'List open files for a specific PID'],
              ['lsof -u alice', 'List open files for user alice'],
              ['lsof -i', 'List all network connections'],
              ['lsof -i :80', 'List processes listening on port 80'],
              ['lsof -i TCP', 'List all TCP connections'],
              ['lsof -i UDP:53', 'List UDP connections on port 53'],
              ['lsof +D /mnt', 'All open files under /mnt (recursive) — helps with umount'],
              ['fuser /mnt', 'Find processes using /mnt (simpler than lsof)'],
              ['fuser -k /mnt', 'Kill all processes using /mnt'],
            ],
          },
          {
            type: 'code',
            text: '# Find what process has a file open\nlsof /var/log/nginx/error.log\n\n# Find process listening on port 443\nlsof -i :443\n# or:\nss -tlnp | grep 443\n\n# Find all deleted files still held open (taking disk space)\nlsof | grep deleted\n\n# Show all files process 1234 has open\nlsof -p 1234\n\n# Find processes using a mount before umount\nfuser -m /mnt/usb\nlsof +D /mnt/usb',
          },
          {
            type: 'h2',
            text: 'screen and tmux — Terminal Multiplexers',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['screen', 'Start a new screen session'],
              ['screen -S name', 'Start named session'],
              ['screen -ls', 'List sessions'],
              ['screen -r name', 'Reattach to named session'],
              ['Ctrl+A D', 'Detach from screen session (session keeps running)'],
              ['tmux', 'Start a new tmux session'],
              ['tmux new -s name', 'Start named tmux session'],
              ['tmux ls', 'List tmux sessions'],
              ['tmux attach -t name', 'Attach to named session'],
              ['Ctrl+B D', 'Detach from tmux session'],
            ],
          },
          {
            type: 'exam',
            title: 'Exam Tips',
            body: 'SIGKILL (9) cannot be caught or ignored — process dies immediately. SIGTERM (15) is the default kill signal. SIGHUP (1) is used to reload config files. Ctrl+C sends SIGINT (2). Ctrl+Z sends SIGTSTP (20) — suspends process. nohup ignores SIGHUP so process survives logout. ps aux (BSD style) vs ps -ef (UNIX style) — both show all processes. pgrep returns PIDs by name; pkill sends signals by name. /proc/PID/ provides per-process info. Load average > nproc indicates overload. zombie processes have exited but parent has not called wait().',
          },
        ],
      },
      {
        id: '103.6',
        topicId: '103',
        title: 'Modify Process Execution Priorities',
        weight: 2,
        description:
          'Understand nice values and use nice and renice to change process scheduling priority.',
        sections: [
          {
            type: 'h2',
            text: 'Nice Values',
          },
          {
            type: 'p',
            text: 'Nice values determine how much CPU time a process gets relative to others. Range: -20 (highest priority) to +19 (lowest priority). Default nice value is 0.',
          },
          {
            type: 'info',
            title: 'Tip',
            body: 'Think of it as "how nice is this process to others?" — a HIGH nice value means the process is very nice, yielding CPU to others. A nice value of -20 is selfish (gets maximum priority).',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['nice -n N cmd', 'Start command with nice value N'],
              ['nice -N cmd', 'Same: start with value N (shorthand)'],
              ['renice -n N -p PID', 'Change nice value of running process PID'],
              ['renice -n N -u user', 'Change nice value for all processes owned by user'],
              ['renice -n N -g group', 'Change nice value for all processes in group'],
            ],
          },
          {
            type: 'code',
            text: '# Start a backup process with low priority (nice = 10)\nnice -n 10 tar -czf backup.tar.gz /home/\n\n# Renice a running process\nrenice -n 5 -p 1234\n\n# Check nice values in top (NI column) or ps\nps -o pid,ni,comm -p 1234\n\n# Only root can set negative nice values\nsudo nice -n -5 ./important_process',
          },
          {
            type: 'warning',
            title: 'Permissions',
            body: 'Regular users can only increase nice values (lower priority). Only root can set negative nice values (increase priority) or renice to a lower value than current.',
          },
          {
            type: 'h2',
            text: 'ionice — I/O Scheduling Priority',
          },
          {
            type: 'p',
            text: 'ionice sets or gets the I/O scheduling class and priority for a program, using the CFQ (Completely Fair Queuing) I/O scheduler.',
          },
          {
            type: 'table',
            headers: ['Class', 'Number', 'Description'],
            rows: [
              ['Real-time (RT)', '1', 'Highest I/O priority. Given first access to disk. Use only for critical tasks. Can starve other processes.'],
              ['Best-effort (BE)', '2', 'Default class. 8 priority levels (0=highest, 7=lowest). Default level is 4.'],
              ['Idle', '3', 'Only gets I/O time when no other process needs it. Ideal for background tasks.'],
            ],
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              ['ionice -c 3 cmd', 'Run command with idle I/O class'],
              ['ionice -c 2 -n 7 cmd', 'Run with best-effort, lowest priority (7)'],
              ['ionice -c 1 -n 0 cmd', 'Run with real-time, highest priority (root only)'],
              ['ionice -p PID', 'Get current I/O class/priority of existing process'],
              ['ionice -c 3 -p PID', 'Set existing process to idle I/O class'],
            ],
          },
          {
            type: 'code',
            text: '# Run a backup with the lowest I/O priority\nionice -c 3 nice -n 19 tar -czf /backup/home.tar.gz /home/\n\n# Check current ionice of a process\nionice -p 1234\n\n# Change a running process to idle I/O class\nionice -c 3 -p $(pgrep updatedb)\n\n# Combine with nice for minimal system impact\nnice -n 19 ionice -c 3 find / -name "*.log" > logfiles.txt',
          },
          {
            type: 'exam',
            title: 'Exam Tips',
            body: 'nice -20 = highest CPU priority. nice +19 = lowest CPU priority. Default is 0. Only root can use negative nice values (or renice lower than current). renice changes existing process priority. In ps, the NI column shows nice value, PRI shows actual kernel priority. ionice sets I/O scheduling class: 1=real-time, 2=best-effort (default), 3=idle. ionice -c 3 makes the process only get I/O when nothing else needs it.',
          },
        ],
      },
      {
        id: '103.7',
        topicId: '103',
        title: 'Search Text Files Using Regular Expressions',
        weight: 3,
        description:
          'Create and use regular expressions for searching text with grep, egrep, and sed.',
        sections: [
          {
            type: 'h2',
            text: 'Basic Regular Expression (BRE) Syntax',
          },
          {
            type: 'table',
            headers: ['Pattern', 'Matches'],
            rows: [
              ['.', 'Any single character (except newline)'],
              ['*', 'Zero or more of the preceding character'],
              ['^', 'Beginning of line'],
              ['$', 'End of line'],
              ['[abc]', 'Any one character: a, b, or c'],
              ['[^abc]', 'Any character NOT a, b, or c'],
              ['[a-z]', 'Any lowercase letter'],
              ['\\\\', 'Literal backslash'],
              ['\\\.', 'Literal dot (escape metachar)'],
              ['\\(\\)', 'Grouping (BRE)'],
              ['\\{2,4\\}', 'Between 2 and 4 of preceding (BRE)'],
            ],
          },
          {
            type: 'h2',
            text: 'Extended Regular Expression (ERE) Syntax',
          },
          {
            type: 'p',
            text: 'ERE (used by grep -E, egrep, sed -E) adds convenience metacharacters:',
          },
          {
            type: 'table',
            headers: ['Pattern', 'Matches'],
            rows: [
              ['+', 'One or more of preceding'],
              ['?', 'Zero or one of preceding'],
              ['|', 'Alternation (OR)'],
              ['()', 'Grouping'],
              ['{2,4}', 'Between 2 and 4 of preceding'],
            ],
          },
          {
            type: 'h2',
            text: 'POSIX Character Classes',
          },
          {
            type: 'table',
            headers: ['Class', 'Equivalent'],
            rows: [
              ['[:alpha:]', 'Alphabetic [a-zA-Z]'],
              ['[:digit:]', 'Digits [0-9]'],
              ['[:alnum:]', 'Alphanumeric [a-zA-Z0-9]'],
              ['[:space:]', 'Whitespace (space, tab, newline...)'],
              ['[:upper:]', 'Uppercase [A-Z]'],
              ['[:lower:]', 'Lowercase [a-z]'],
              ['[:punct:]', 'Punctuation characters'],
            ],
          },
          {
            type: 'code',
            text: '# BRE: grep (basic regex)\ngrep \'^root\' /etc/passwd             # lines starting with "root"\ngrep \'bash$\' /etc/passwd             # lines ending with "bash"\ngrep \'[0-9]\\{3\\}\' file              # 3 consecutive digits (BRE)\ngrep \'.\' file                        # non-empty lines\n\n# ERE: grep -E or egrep\ngrep -E \'(root|admin)\' /etc/passwd   # "root" OR "admin"\ngrep -E \'[0-9]{3,}\' file             # 3 or more digits\ngrep -E \'^[A-Z][a-z]+\' file         # Capitalized word at line start\ngrep -E \'https?://\' file            # http or https\n\n# sed with regex\nsed \'s/[0-9]\\+/NUM/g\' file           # replace all number sequences\nsed -n \'/^[[:space:]]*$/d\' file       # delete blank lines\nsed -E \'s/(error|warning):/[\\1]:/gI\' file',
          },
          {
            type: 'h2',
            text: 'grep Options Reference',
          },
          {
            type: 'table',
            headers: ['Option', 'Description'],
            rows: [
              ['grep -i', 'Case-insensitive match'],
              ['grep -v', 'Invert match (lines NOT matching)'],
              ['grep -c', 'Count matching lines'],
              ['grep -l', 'List filenames with matches only'],
              ['grep -L', 'List filenames WITHOUT matches'],
              ['grep -n', 'Show line numbers with output'],
              ['grep -o', 'Print only the matched part (not full line)'],
              ['grep -r', 'Recursive search through directories'],
              ['grep -w', 'Match whole words only'],
              ['grep -A N', 'Print N lines after match (After)'],
              ['grep -B N', 'Print N lines before match (Before)'],
              ['grep -C N', 'Print N lines around match (Context)'],
              ['grep -E', 'Extended Regular Expressions (ERE)'],
              ['grep -F', 'Fixed strings — no regex interpretation'],
              ['grep -P', 'Perl-compatible regex (PCRE)'],
              ['grep -q', 'Quiet — exit 0 if match found, 1 if not'],
              ['grep -s', 'Suppress error messages for missing files'],
            ],
          },
          {
            type: 'h2',
            text: 'Practical grep Examples',
          },
          {
            type: 'code',
            text: '# Find all login failures in auth.log\ngrep -i "failed" /var/log/auth.log\n\n# Show failed login attempts with 3 lines of context\ngrep -C3 "Failed password" /var/log/auth.log\n\n# Count how many lines match\ngrep -c "error" /var/log/syslog\n\n# List files containing "TODO"\ngrep -rl "TODO" /project/src/\n\n# Match whole word "cat" (not "concatenate")\ngrep -w "cat" animals.txt\n\n# Show only the matching portion\ngrep -oE "[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+" /var/log/httpd/access.log\n\n# Find lines NOT containing "comment"\ngrep -v "^#" /etc/ssh/sshd_config | grep -v "^$"\n\n# Recursive case-insensitive search\ngrep -rin "password" /etc/*.conf',
          },
          {
            type: 'exam',
            title: 'Exam Tips',
            body: 'BRE uses \\( \\) \\{ \\} for grouping and quantifiers. ERE uses () {} + ? | without backslashes. grep uses BRE, grep -E uses ERE. egrep = grep -E (deprecated, use grep -E). fgrep = grep -F (fixed strings, no regex). ^ anchors to start, $ to end of line. grep -i = case-insensitive. grep -v = invert match. grep -c = count matches. grep -l = list filenames only. grep -r = recursive. grep -n = show line numbers. grep -o = only print matching part. Use single quotes around patterns to avoid shell expansion.',
          },
        ],
      },
      {
        id: '103.8',
        topicId: '103',
        title: 'Basic File Editing with vi',
        weight: 3,
        description:
          'Navigate and edit text files using the vi/vim editor: modes, commands, search and replace.',
        sections: [
          {
            type: 'h2',
            text: 'vi Modes',
          },
          {
            type: 'table',
            headers: ['Mode', 'Entry', 'Description'],
            rows: [
              ['Normal (Command)', 'Esc (from any mode)', 'Navigate, execute commands. Default starting mode.'],
              ['Insert', 'i, I, a, A, o, O (from Normal)', 'Type text; changes the file'],
              ['Visual', 'v, V, Ctrl+V (from Normal)', 'Select text; then apply commands'],
              ['Command-line', ': / ? (from Normal)', 'Enter ex commands, search'],
            ],
          },
          {
            type: 'h2',
            text: 'Entering Insert Mode',
          },
          {
            type: 'table',
            headers: ['Key', 'Description'],
            rows: [
              ['i', 'Insert before cursor'],
              ['I', 'Insert at beginning of line'],
              ['a', 'Append after cursor'],
              ['A', 'Append at end of line'],
              ['o', 'Open new line below, enter insert'],
              ['O', 'Open new line above, enter insert'],
              ['s', 'Substitute character (delete + insert)'],
              ['S', 'Substitute entire line'],
            ],
          },
          {
            type: 'h2',
            text: 'Navigation (Normal Mode)',
          },
          {
            type: 'table',
            headers: ['Key(s)', 'Movement'],
            rows: [
              ['h j k l', 'Left, Down, Up, Right'],
              ['w / b', 'Next / previous word'],
              ['0 / ^', 'Start of line / first non-blank'],
              ['$', 'End of line'],
              ['gg / G', 'First line / last line of file'],
              ['NNN G or :NNN', 'Go to line NNN'],
              ['Ctrl+F / Ctrl+B', 'Page forward / backward'],
              ['%', 'Jump to matching bracket'],
            ],
          },
          {
            type: 'h2',
            text: 'Editing Commands (Normal Mode)',
          },
          {
            type: 'table',
            headers: ['Key', 'Action'],
            rows: [
              ['x', 'Delete character under cursor'],
              ['dd', 'Delete (cut) entire line'],
              ['NNdd', 'Delete NN lines'],
              ['yy', 'Yank (copy) line'],
              ['p', 'Paste after cursor/line'],
              ['P', 'Paste before cursor/line'],
              ['u', 'Undo last change'],
              ['Ctrl+R', 'Redo'],
              ['r<char>', 'Replace single character'],
              ['cw', 'Change word'],
              ['cc or S', 'Change entire line'],
              ['.', 'Repeat last change'],
            ],
          },
          {
            type: 'h2',
            text: 'Search and Replace',
          },
          {
            type: 'code',
            text: '# Search forward\n/pattern          # search for pattern\nn                 # next match\nN                 # previous match\n\n# Search backward\n?pattern\n\n# Search and replace (command-line mode)\n:s/old/new/       # replace first on current line\n:s/old/new/g      # replace all on current line\n:%s/old/new/g     # replace all in entire file\n:%s/old/new/gi    # case-insensitive, all file\n:%s/old/new/gc    # with confirmation prompt',
          },
          {
            type: 'h2',
            text: 'Saving and Exiting',
          },
          {
            type: 'table',
            headers: ['Command', 'Action'],
            rows: [
              [':w', 'Save (write) file'],
              [':w filename', 'Save as filename'],
              [':q', 'Quit (fails if unsaved changes)'],
              [':q!', 'Quit without saving (force)'],
              [':wq or :x or ZZ', 'Save and quit'],
              [':wq!', 'Save and quit (force)'],
              ['ZQ', 'Quit without saving'],
            ],
          },
          {
            type: 'h2',
            text: 'Useful vi/vim Commands',
          },
          {
            type: 'table',
            headers: ['Command', 'Description'],
            rows: [
              [':set number', 'Show line numbers'],
              [':set nonumber', 'Hide line numbers'],
              [':set syntax=on', 'Enable syntax highlighting'],
              [':set ignorecase', 'Case-insensitive search'],
              [':set hlsearch', 'Highlight search results'],
              [':nohl', 'Clear search highlighting'],
              [':set expandtab', 'Use spaces instead of tabs'],
              [':set tabstop=4', 'Set tab width to 4 spaces'],
              [':%d', 'Delete all lines in file'],
              [':1,$d', 'Same as :%d'],
              ['J', 'Join current line with next'],
              ['~', 'Toggle case of character under cursor'],
              ['>>  <<', 'Indent line right / left'],
              ['Ctrl+G', 'Show current file info and position'],
              [':e filename', 'Open another file'],
              [':sp filename', 'Split window horizontally'],
              [':vsp filename', 'Split window vertically'],
              ['Ctrl+W W', 'Switch between split windows'],
            ],
          },
          {
            type: 'h2',
            text: '.vimrc — Vi Configuration File',
          },
          {
            type: 'code',
            text: '# ~/.vimrc — personal vim configuration\nset number            " show line numbers\nset tabstop=4         " tab = 4 spaces\nset expandtab         " use spaces instead of tabs\nset autoindent        " auto-indent new lines\nset hlsearch          " highlight search results\nset ignorecase        " case-insensitive search\nset smartcase         " case-sensitive if uppercase in pattern\nset wrap              " wrap long lines\nsyntax on             " syntax highlighting\ncolorscheme desert    " color scheme (optional)\n\n# Apply settings without restarting\n:source ~/.vimrc',
          },
          {
            type: 'exam',
            title: 'Exam Tips',
            body: 'Most important: Esc returns to Normal mode. :wq saves and quits, :q! force-quits, ZZ saves and quits. dd deletes a line, yy copies a line, p pastes. :%s/old/new/g replaces globally in file. vi starts in Normal mode. Always press Esc before entering : commands. /pattern searches forward; ?pattern searches backward; n next, N previous. u = undo, Ctrl+R = redo. :set number shows line numbers. G goes to last line, gg to first line, :50 goes to line 50.',
          },
        ],
      },
    ],
}
