import type { QuizQuestion } from './types'

// ============================================================
// LPI 101-500 Quiz Questions — 10 questions per topic
// ============================================================

export const quizQuestions: QuizQuestion[] = [
  // ============================================================
  // TOPIC 101
  // ============================================================
  {
    id: 'q101-01',
    topicId: '101',
    lessonId: '101.1',
    question: 'Which command lists all currently loaded kernel modules?',
    options: ['modinfo', 'lsmod', 'lspci', 'insmod'],
    correct: 1,
    explanation: 'lsmod reads /proc/modules and displays all currently loaded kernel modules with their size and dependencies.',
    difficulty: 'easy',
  },
  {
    id: 'q101-02',
    topicId: '101',
    lessonId: '101.1',
    question: 'What is the main difference between modprobe and insmod?',
    options: [
      'insmod resolves dependencies; modprobe does not',
      'modprobe resolves dependencies; insmod does not',
      'modprobe only removes modules; insmod only loads them',
      'There is no difference — they are identical commands',
    ],
    correct: 1,
    explanation: 'modprobe automatically handles module dependencies (loading required modules first), while insmod requires you to load all dependencies manually.',
    difficulty: 'medium',
  },
  {
    id: 'q101-03',
    topicId: '101',
    lessonId: '101.1',
    question: 'Which file in /proc contains information about IRQ assignments?',
    options: ['/proc/dma', '/proc/ioports', '/proc/interrupts', '/proc/cpuinfo'],
    correct: 2,
    explanation: '/proc/interrupts shows IRQ numbers, the number of interrupts per CPU, the interrupt type, and the device involved.',
    difficulty: 'medium',
  },
  {
    id: 'q101-04',
    topicId: '101',
    lessonId: '101.2',
    question: 'In what order does the standard Linux boot process occur?',
    options: [
      'Kernel → BIOS → GRUB → init',
      'BIOS → GRUB → Kernel → init',
      'GRUB → BIOS → Kernel → init',
      'BIOS → Kernel → GRUB → init',
    ],
    correct: 1,
    explanation: 'The correct order is: BIOS/UEFI (POST) → GRUB2 boot loader → Linux Kernel loads → init/systemd (PID 1) starts.',
    difficulty: 'easy',
  },
  {
    id: 'q101-05',
    topicId: '101',
    lessonId: '101.2',
    question: 'Which command shows kernel boot messages from the current boot?',
    options: ['syslog', 'bootlog', 'dmesg', 'kern.log'],
    correct: 2,
    explanation: 'dmesg prints the kernel ring buffer which contains messages generated during boot and from kernel subsystems/drivers.',
    difficulty: 'easy',
  },
  {
    id: 'q101-06',
    topicId: '101',
    lessonId: '101.2',
    question: 'What file is edited to change GRUB2 settings like the boot timeout?',
    options: [
      '/boot/grub/grub.cfg',
      '/etc/default/grub',
      '/etc/grub.d/00_header',
      '/boot/grub/menu.lst',
    ],
    correct: 1,
    explanation: '/etc/default/grub contains user-configurable GRUB2 settings. After editing, run update-grub or grub-mkconfig to regenerate /boot/grub/grub.cfg.',
    difficulty: 'medium',
  },
  {
    id: 'q101-07',
    topicId: '101',
    lessonId: '101.3',
    question: 'What is runlevel 1 used for in SysV init?',
    options: ['Normal multi-user mode', 'Graphical mode', 'Single-user/rescue mode', 'Reboot'],
    correct: 2,
    explanation: 'Runlevel 1 (also called "S" or single-user mode) is maintenance mode with networking disabled. It corresponds to systemd\'s rescue.target.',
    difficulty: 'easy',
  },
  {
    id: 'q101-08',
    topicId: '101',
    lessonId: '101.3',
    question: 'Which systemd command shows the default target?',
    options: [
      'systemctl default',
      'systemctl get-default',
      'systemctl show-target',
      'runlevel',
    ],
    correct: 1,
    explanation: 'systemctl get-default shows the current default target unit. To change it, use systemctl set-default <target>.',
    difficulty: 'easy',
  },
  {
    id: 'q101-09',
    topicId: '101',
    lessonId: '101.3',
    question: 'Which command schedules a system shutdown in 10 minutes with a wall message?',
    options: [
      'shutdown -h now "Maintenance"',
      'shutdown -h +10 "Maintenance"',
      'halt +10 "Maintenance"',
      'poweroff -t 600',
    ],
    correct: 1,
    explanation: 'shutdown -h +10 "Maintenance" halts the system after 10 minutes and broadcasts the message to all logged-in users with wall.',
    difficulty: 'medium',
  },
  {
    id: 'q101-10',
    topicId: '101',
    lessonId: '101.1',
    question: 'The /sys filesystem provides what kind of information?',
    options: [
      'Running process information',
      'User account data',
      'Kernel device model and hardware attributes',
      'Network routing tables',
    ],
    correct: 2,
    explanation: '/sys (sysfs) exposes the kernel\'s internal device model as a directory tree, allowing userspace programs to read and sometimes configure hardware attributes.',
    difficulty: 'medium',
  },
  {
    id: 'q101-11',
    topicId: '101',
    lessonId: '101.1',
    question: 'What does /dev/zero return when read?',
    options: ['EOF immediately', 'Random bytes', 'Infinite null (zero) bytes', 'The contents of /dev/null'],
    correct: 2,
    explanation: '/dev/zero returns an endless stream of null bytes (0x00). It is commonly used to zero-fill files or wipe storage. /dev/null discards writes and returns EOF on reads.',
    difficulty: 'easy',
  },
  {
    id: 'q101-12',
    topicId: '101',
    lessonId: '101.1',
    question: 'What is the device name for the first partition on an NVMe SSD?',
    options: ['/dev/sda1', '/dev/nvme0n1', '/dev/nvme0n1p1', '/dev/nvme0p1'],
    correct: 2,
    explanation: 'NVMe devices follow the format /dev/nvme<controller>n<namespace>. Partitions use a "p" prefix: /dev/nvme0n1p1, /dev/nvme0n1p2, etc.',
    difficulty: 'medium',
  },
  {
    id: 'q101-13',
    topicId: '101',
    lessonId: '101.1',
    question: 'Which /proc file shows I/O port address ranges assigned to devices?',
    options: ['/proc/interrupts', '/proc/dma', '/proc/ioports', '/proc/iomem'],
    correct: 2,
    explanation: '/proc/ioports lists the I/O port address ranges used by hardware devices. For example, COM1 uses 0x03f8-0x03ff.',
    difficulty: 'medium',
  },
  {
    id: 'q101-14',
    topicId: '101',
    lessonId: '101.1',
    question: 'What is the default IRQ number for COM1 (ttyS0)?',
    options: ['IRQ 1', 'IRQ 3', 'IRQ 4', 'IRQ 6'],
    correct: 2,
    explanation: 'COM1 (ttyS0) uses IRQ 4 at I/O address 0x03F8. COM2 (ttyS1) uses IRQ 3 at 0x02F8. IRQ 1 is keyboard, IRQ 6 is floppy.',
    difficulty: 'medium',
  },
  {
    id: 'q101-15',
    topicId: '101',
    lessonId: '101.1',
    question: 'Which SATA controller mode is recommended for modern Linux systems?',
    options: ['IDE (Legacy)', 'RAID', 'AHCI', 'SCSI'],
    correct: 2,
    explanation: 'AHCI (Advanced Host Controller Interface) is recommended — it supports hot-plug and NCQ. Switching modes after OS installation can break the boot.',
    difficulty: 'easy',
  },
  {
    id: 'q101-16',
    topicId: '101',
    lessonId: '101.1',
    question: 'Which command displays detailed information about a kernel module (description, parameters, author)?',
    options: ['lsmod e1000', 'modprobe --info e1000', 'modinfo e1000', 'insmod -i e1000'],
    correct: 2,
    explanation: 'modinfo displays a module\'s filename, description, license, author, version, and accepted parameters. Use it to inspect a module before loading.',
    difficulty: 'easy',
  },
  {
    id: 'q101-17',
    topicId: '101',
    lessonId: '101.1',
    question: 'Which command unloads a kernel module AND its unused dependencies automatically?',
    options: ['rmmod', 'modprobe -r', 'insmod -d', 'depmod -r'],
    correct: 1,
    explanation: 'modprobe -r removes a module and any of its dependencies that are no longer needed. rmmod removes only the specified module and fails if dependencies still use it.',
    difficulty: 'medium',
  },
  {
    id: 'q101-18',
    topicId: '101',
    lessonId: '101.1',
    question: 'Which lspci option shows the kernel driver currently in use for each PCI device?',
    options: ['lspci -v', 'lspci -k', 'lspci -nn', 'lspci -t'],
    correct: 1,
    explanation: 'lspci -k shows each PCI device alongside the kernel driver handling it. This is the fastest way to verify which driver is bound to a piece of hardware.',
    difficulty: 'easy',
  },
  {
    id: 'q101-19',
    topicId: '101',
    lessonId: '101.1',
    question: 'Where are user-defined udev rules stored?',
    options: ['/etc/udev/rules.d/', '/lib/udev/rules.d/', '/proc/udev/', '/dev/rules.d/'],
    correct: 0,
    explanation: 'Custom udev rules go in /etc/udev/rules.d/. System-provided rules are in /lib/udev/rules.d/. Files in /etc take precedence over /lib.',
    difficulty: 'medium',
  },
  {
    id: 'q101-20',
    topicId: '101',
    lessonId: '101.1',
    question: 'To prevent a module from loading automatically, which directory should you edit?',
    options: ['/etc/modules', '/etc/modules-load.d/*.conf', '/etc/modprobe.d/*.conf', '/lib/modules/modules.dep'],
    correct: 2,
    explanation: 'Blacklisting is configured in /etc/modprobe.d/*.conf with the syntax: "blacklist <module_name>". This prevents the module from being auto-loaded by udev.',
    difficulty: 'medium',
  },
  {
    id: 'q101-21',
    topicId: '101',
    lessonId: '101.1',
    question: 'On a systemd-based system, which file specifies modules to load at boot time?',
    options: ['/etc/modules', '/etc/modules-load.d/*.conf', '/etc/modprobe.d/*.conf', '/proc/modules'],
    correct: 1,
    explanation: 'On systemd systems, /etc/modules-load.d/*.conf lists modules to load at boot. Older Debian/Ubuntu systems used /etc/modules instead.',
    difficulty: 'medium',
  },
  {
    id: 'q101-22',
    topicId: '101',
    lessonId: '101.1',
    question: 'A USB drive plugged in while the system is running is an example of which device type?',
    options: ['Cold plug', 'Hot plug', 'Warm plug', 'PCI plug'],
    correct: 1,
    explanation: 'USB is hot-plug: devices can be connected/disconnected while the system runs. udev detects the kernel uevent and automatically creates the /dev node and loads the driver.',
    difficulty: 'easy',
  },
  {
    id: 'q101-23',
    topicId: '101',
    lessonId: '101.1',
    question: 'Which udevadm subcommand monitors device events in real time?',
    options: ['udevadm info', 'udevadm trigger', 'udevadm monitor', 'udevadm settle'],
    correct: 2,
    explanation: 'udevadm monitor listens for kernel uevents and udev events, printing them as they occur. Useful for debugging hotplug behavior when connecting hardware.',
    difficulty: 'easy',
  },
  {
    id: 'q101-24',
    topicId: '101',
    lessonId: '101.1',
    question: 'What does DMA (Direct Memory Access) allow a hardware device to do?',
    options: [
      'Directly execute CPU instructions',
      'Transfer data to/from RAM without involving the CPU',
      'Access the kernel virtual memory space',
      'Bypass the /proc filesystem',
    ],
    correct: 1,
    explanation: 'DMA lets a hardware device transfer data directly to system RAM without CPU intervention, freeing the CPU for other work during large data transfers.',
    difficulty: 'medium',
  },
  {
    id: 'q101-25',
    topicId: '101',
    lessonId: '101.1',
    question: 'Which command displays CPU architecture details including number of cores, threads, and cache sizes?',
    options: ['lspci', 'lsusb', 'lscpu', 'dmidecode'],
    correct: 2,
    explanation: 'lscpu reads /proc/cpuinfo and other sources to present a structured view of CPU architecture: sockets, cores per socket, threads, cache hierarchy, etc.',
    difficulty: 'easy',
  },

  // ============================================================
  // TOPIC 102
  // ============================================================
  {
    id: 'q102-01',
    topicId: '102',
    lessonId: '102.1',
    question: 'Which directory should ideally be on a separate partition to prevent it from filling up the root filesystem on a busy server?',
    options: ['/home', '/var', '/usr', '/opt'],
    correct: 1,
    explanation: '/var contains variable data: logs, databases, mail spools, and print queues. These can grow unpredictably and filling /var on the root partition can crash the system.',
    difficulty: 'easy',
  },
  {
    id: 'q102-02',
    topicId: '102',
    lessonId: '102.2',
    question: 'After editing /etc/default/grub on a Debian/Ubuntu system, which command regenerates the GRUB2 configuration file?',
    options: ['grub-install', 'grub-update', 'update-grub', 'grub-mkconfig'],
    correct: 2,
    explanation: 'update-grub is the Debian/Ubuntu shorthand that runs grub-mkconfig -o /boot/grub/grub.cfg to regenerate the GRUB2 configuration.',
    difficulty: 'easy',
  },
  {
    id: 'q102-03',
    topicId: '102',
    lessonId: '102.3',
    question: 'Which command rebuilds the shared library cache (/etc/ld.so.cache)?',
    options: ['ldd', 'ldconfig', 'libcache', 'update-libs'],
    correct: 1,
    explanation: 'ldconfig rebuilds the dynamic linker cache /etc/ld.so.cache by scanning the directories listed in /etc/ld.so.conf. Run it after installing new shared libraries.',
    difficulty: 'easy',
  },
  {
    id: 'q102-04',
    topicId: '102',
    lessonId: '102.3',
    question: 'Which command shows the shared libraries required by a given executable?',
    options: ['ldd', 'ldconfig', 'nm', 'objdump'],
    correct: 0,
    explanation: 'ldd (list dynamic dependencies) prints all shared libraries needed by an executable, along with the path where they will be loaded from.',
    difficulty: 'easy',
  },
  {
    id: 'q102-05',
    topicId: '102',
    lessonId: '102.4',
    question: 'Which dpkg command shows which package a specific file belongs to?',
    options: ['dpkg -L', 'dpkg -S', 'dpkg -s', 'dpkg -l'],
    correct: 1,
    explanation: 'dpkg -S <file> searches the dpkg database for the package that installed a specific file. For example: dpkg -S /bin/ls returns coreutils.',
    difficulty: 'medium',
  },
  {
    id: 'q102-06',
    topicId: '102',
    lessonId: '102.4',
    question: 'Which file defines the APT package repositories?',
    options: ['/etc/apt/preferences', '/etc/apt/sources.list', '/var/lib/apt/lists/', '/etc/apt/apt.conf'],
    correct: 1,
    explanation: '/etc/apt/sources.list (and files in /etc/apt/sources.list.d/) contain the list of APT repositories. Each line specifies a URL, distribution, and components.',
    difficulty: 'easy',
  },
  {
    id: 'q102-07',
    topicId: '102',
    lessonId: '102.5',
    question: 'Which rpm command shows which installed package owns /bin/bash?',
    options: ['rpm -ql bash', 'rpm -qi /bin/bash', 'rpm -qf /bin/bash', 'rpm -qa /bin/bash'],
    correct: 2,
    explanation: 'rpm -qf <file> (query file) identifies which package owns a given file. For example: rpm -qf /bin/bash returns bash-version.',
    difficulty: 'medium',
  },
  {
    id: 'q102-08',
    topicId: '102',
    lessonId: '102.5',
    question: 'What is the key advantage of yum/dnf over rpm?',
    options: [
      'yum/dnf can install .deb packages',
      'yum/dnf automatically resolves package dependencies',
      'yum/dnf is faster than rpm',
      'yum/dnf works without root access',
    ],
    correct: 1,
    explanation: 'yum and dnf automatically download and install required dependencies, while rpm requires you to manually install all dependencies first.',
    difficulty: 'easy',
  },
  {
    id: 'q102-09',
    topicId: '102',
    lessonId: '102.1',
    question: 'Which partition type code is used for Linux swap in fdisk?',
    options: ['81', '82', '83', '8e'],
    correct: 1,
    explanation: 'In fdisk, partition type 82 = Linux swap, 83 = Linux (regular data), 8e = Linux LVM. Type 82 must be set for swap partitions to be recognized.',
    difficulty: 'hard',
  },
  {
    id: 'q102-10',
    topicId: '102',
    lessonId: '102.6',
    question: 'Which command detects whether the current system is running inside a virtual machine?',
    options: ['virt-what', 'systemd-detect-virt', 'lshw --virt', 'dmidecode -virt'],
    correct: 1,
    explanation: 'systemd-detect-virt detects and reports the type of virtualization (e.g., kvm, xen, vmware, docker, none). It returns a non-zero exit code if not virtualized.',
    difficulty: 'medium',
  },

  // ============================================================
  // TOPIC 103
  // ============================================================
  {
    id: 'q103-01',
    topicId: '103',
    lessonId: '103.1',
    question: 'What does the !! expansion do in bash?',
    options: [
      'Runs the command twice',
      'Re-runs the last executed command',
      'Runs the command as root',
      'Displays all history entries',
    ],
    correct: 1,
    explanation: '!! is a history expansion that substitutes and re-executes the most recently run command. Useful for: sudo !! to re-run the last command with sudo.',
    difficulty: 'easy',
  },
  {
    id: 'q103-02',
    topicId: '103',
    lessonId: '103.1',
    question: 'Which command identifies whether "ls" is an alias, builtin, or external command?',
    options: ['which ls', 'whereis ls', 'type ls', 'file ls'],
    correct: 2,
    explanation: 'type <command> tells you exactly what a name refers to: alias, shell builtin, function, or an external file. which only searches PATH for executables.',
    difficulty: 'easy',
  },
  {
    id: 'q103-03',
    topicId: '103',
    lessonId: '103.2',
    question: 'Which command counts the number of lines in a file?',
    options: ['wc -w', 'wc -l', 'wc -c', 'count -l'],
    correct: 1,
    explanation: 'wc -l counts lines. wc -w counts words, wc -c counts bytes, wc -m counts characters.',
    difficulty: 'easy',
  },
  {
    id: 'q103-04',
    topicId: '103',
    lessonId: '103.2',
    question: 'You want to display only lines from access.log that do NOT contain "200". Which command?',
    options: ['grep "200" access.log', 'grep -v "200" access.log', 'grep -i "200" access.log', 'grep -l "200" access.log'],
    correct: 1,
    explanation: 'grep -v (invert) prints lines that do NOT match the pattern. This is useful for filtering out known-good entries or excluding specific patterns.',
    difficulty: 'easy',
  },
  {
    id: 'q103-05',
    topicId: '103',
    lessonId: '103.3',
    question: 'Which tar option creates a gzip-compressed archive?',
    options: ['-cvf', '-czvf', '-cjvf', '-cJvf'],
    correct: 1,
    explanation: 'tar -czvf: c=create, z=gzip-compress, v=verbose, f=file. For bzip2 use -j, for xz use -J.',
    difficulty: 'easy',
  },
  {
    id: 'q103-06',
    topicId: '103',
    lessonId: '103.4',
    question: 'What does the command "cmd > /dev/null 2>&1" do?',
    options: [
      'Redirects stdout to /dev/null and stderr to stdout (discards both)',
      'Redirects stderr to /dev/null and stdout to a file',
      'Duplicates stdout to stderr',
      'Redirects both streams to the terminal',
    ],
    correct: 0,
    explanation: '> /dev/null redirects stdout to /dev/null (discard). 2>&1 then redirects stderr to the same destination as stdout (also /dev/null). Result: both stdout and stderr are discarded.',
    difficulty: 'medium',
  },
  {
    id: 'q103-07',
    topicId: '103',
    lessonId: '103.5',
    question: 'Which signal cannot be caught or ignored by a process?',
    options: ['SIGTERM (15)', 'SIGINT (2)', 'SIGKILL (9)', 'SIGHUP (1)'],
    correct: 2,
    explanation: 'SIGKILL (signal 9) immediately terminates a process and cannot be caught, blocked, or ignored. This is why kill -9 always works (unless the process is in an uninterruptible sleep state).',
    difficulty: 'medium',
  },
  {
    id: 'q103-08',
    topicId: '103',
    lessonId: '103.5',
    question: 'Which command brings a background job (job number 2) to the foreground?',
    options: ['bg %2', 'fg %2', 'jobs %2', 'resume 2'],
    correct: 1,
    explanation: 'fg %2 brings job number 2 to the foreground. Use jobs to list current jobs and their numbers. bg %N resumes a stopped job in the background.',
    difficulty: 'easy',
  },
  {
    id: 'q103-09',
    topicId: '103',
    lessonId: '103.6',
    question: 'What is the nice value range in Linux?',
    options: [
      '0 to 100 (higher = more priority)',
      '-20 to +19 (lower = more priority)',
      '-19 to +20 (lower = more priority)',
      '1 to 40 (higher = more priority)',
    ],
    correct: 1,
    explanation: 'Nice values range from -20 (highest CPU priority, very "not nice" to others) to +19 (lowest CPU priority, very friendly). Default is 0.',
    difficulty: 'medium',
  },
  {
    id: 'q103-10',
    topicId: '103',
    lessonId: '103.8',
    question: 'In vi, which command saves the file and exits the editor?',
    options: [':q', ':w', ':wq', ':save'],
    correct: 2,
    explanation: ':wq writes (saves) the file and quits vi. :w saves without quitting. :q quits (fails if unsaved changes exist). :q! force-quits without saving.',
    difficulty: 'easy',
  },

  // ============================================================
  // TOPIC 104
  // ============================================================
  {
    id: 'q104-01',
    topicId: '104',
    lessonId: '104.1',
    question: 'Which command is used to initialise a swap partition?',
    options: ['swapon', 'mkswap', 'mkfs.swap', 'format-swap'],
    correct: 1,
    explanation: 'mkswap initialises a partition or file as swap space (writes swap header). After that, swapon activates it.',
    difficulty: 'easy',
  },
  {
    id: 'q104-02',
    topicId: '104',
    lessonId: '104.2',
    question: 'Before running fsck on a filesystem, what must you do?',
    options: [
      'Back up the filesystem',
      'Unmount the filesystem',
      'Set it to read-only with mount -o ro',
      'Run tune2fs -c 1',
    ],
    correct: 1,
    explanation: 'fsck must only be run on unmounted filesystems. Running fsck on a mounted filesystem can cause severe data corruption.',
    difficulty: 'easy',
  },
  {
    id: 'q104-03',
    topicId: '104',
    lessonId: '104.2',
    question: 'Which command shows filesystem disk space usage in human-readable format?',
    options: ['du -h', 'df -h', 'ls -sh', 'fdisk -h'],
    correct: 1,
    explanation: 'df -h shows disk space usage for all mounted filesystems in human-readable format (KB, MB, GB). du -h shows usage per file/directory.',
    difficulty: 'easy',
  },
  {
    id: 'q104-04',
    topicId: '104',
    lessonId: '104.3',
    question: 'What does the 6th field in /etc/fstab control?',
    options: [
      'Mount options',
      'Filesystem type',
      'fsck check order (0=skip, 1=first, 2=after)',
      'Whether to mount at boot',
    ],
    correct: 2,
    explanation: 'The 6th field (pass) in /etc/fstab controls fsck check order: 0=skip, 1=check first (should be root FS), 2=check after root. This helps find errors during boot.',
    difficulty: 'hard',
  },
  {
    id: 'q104-05',
    topicId: '104',
    lessonId: '104.5',
    question: 'What octal permission value represents rwxr-xr-x?',
    options: ['766', '755', '644', '777'],
    correct: 1,
    explanation: 'rwx=7, r-x=5, r-x=5. So rwxr-xr-x = 755. r=4, w=2, x=1. Owner: 4+2+1=7, Group: 4+0+1=5, Others: 4+0+1=5.',
    difficulty: 'easy',
  },
  {
    id: 'q104-06',
    topicId: '104',
    lessonId: '104.5',
    question: 'What is the effect of the SUID bit on an executable file?',
    options: [
      'Only root can execute the file',
      'The file executes with the permissions of the file owner, not the caller',
      'The file is executable by the owner only',
      'New files created in the same directory inherit ownership',
    ],
    correct: 1,
    explanation: 'SUID (Set User ID): when set on an executable, it runs with the permissions of the file\'s owner rather than the user who launched it. Classic example: /usr/bin/passwd runs as root so it can modify /etc/shadow.',
    difficulty: 'medium',
  },
  {
    id: 'q104-07',
    topicId: '104',
    lessonId: '104.5',
    question: 'With a umask of 027, what permissions will a newly created file have?',
    options: ['640', '750', '755', '644'],
    correct: 0,
    explanation: 'Files default to 666. umask 027: 666 - 027 = 640 (rw-r-----). Directories default to 777: 777 - 027 = 750 (rwxr-x---).',
    difficulty: 'hard',
  },
  {
    id: 'q104-08',
    topicId: '104',
    lessonId: '104.6',
    question: 'Which statement about hard links is correct?',
    options: [
      'A hard link can span across different filesystems',
      'Deleting a hard link immediately deletes the file data',
      'A hard link and its target share the same inode number',
      'Hard links can be created for directories',
    ],
    correct: 2,
    explanation: 'Hard links share the same inode (same data, same metadata). They cannot cross filesystems. Data is only deleted when all hard links (link count reaches 0) are removed. Hard links to directories are generally not allowed.',
    difficulty: 'medium',
  },
  {
    id: 'q104-09',
    topicId: '104',
    lessonId: '104.7',
    question: 'Which directory contains non-essential user command binaries (above and beyond /bin)?',
    options: ['/sbin', '/usr/sbin', '/usr/bin', '/usr/local'],
    correct: 2,
    explanation: '/usr/bin contains non-essential user command binaries (e.g., git, python3, gcc). /bin contains only essential binaries needed for single-user boot/recovery.',
    difficulty: 'medium',
  },
  {
    id: 'q104-10',
    topicId: '104',
    lessonId: '104.7',
    question: 'Which command searches for files using a pre-built database for fast results?',
    options: ['find', 'locate', 'which', 'whereis'],
    correct: 1,
    explanation: 'locate searches a pre-built database (updated by updatedb) making it very fast. find searches the filesystem in real-time which is slower but always up-to-date.',
    difficulty: 'easy',
  },

  // ============================================================
  // TOPIC 105
  // ============================================================
  {
    id: 'q105-01',
    topicId: '105',
    lessonId: '105.1',
    question: 'Which file is sourced by bash for a non-login interactive shell?',
    options: ['~/.bash_profile', '~/.bashrc', '~/.profile', '/etc/profile'],
    correct: 1,
    explanation: '~/.bashrc is sourced for non-login interactive shells. ~/.bash_profile (or ~/.profile) is for login shells. /etc/profile applies to all login shells system-wide.',
    difficulty: 'easy',
  },
  {
    id: 'q105-02',
    topicId: '105',
    lessonId: '105.1',
    question: 'What does the export command do to a shell variable?',
    options: [
      'Saves the variable to a file',
      'Makes the variable available to child processes as an environment variable',
      'Copies the variable to /etc/environment',
      'Makes the variable read-only',
    ],
    correct: 1,
    explanation: 'export marks a variable for export to child processes\' environments. Without export, a variable is only visible in the current shell session.',
    difficulty: 'easy',
  },
  {
    id: 'q105-03',
    topicId: '105',
    lessonId: '105.2',
    question: 'In a bash script, what does $? represent?',
    options: ['The PID of the script', 'The exit status of the last command', 'The number of arguments', 'The name of the script'],
    correct: 1,
    explanation: '$? holds the exit status of the most recently executed command. 0 means success; non-zero indicates failure.',
    difficulty: 'easy',
  },
  {
    id: 'q105-04',
    topicId: '105',
    lessonId: '105.2',
    question: 'What is the correct bash syntax for arithmetic expansion?',
    options: ['$[expr]', '$(expr)', '$((expr))', '${expr}'],
    correct: 2,
    explanation: '$((expr)) is bash arithmetic expansion. Example: $((3 + 4)) evaluates to 7. Supports +, -, *, /, %, ** (exponentiation).',
    difficulty: 'easy',
  },
  {
    id: 'q105-05',
    topicId: '105',
    lessonId: '105.2',
    question: 'Which test expression checks if a path exists and is a regular file?',
    options: ['[ -d file ]', '[ -e file ]', '[ -f file ]', '[ -r file ]'],
    correct: 2,
    explanation: '[ -f file ] tests if the path exists and is a regular file. -d=directory, -e=any existence, -r=read permission, -x=execute permission.',
    difficulty: 'medium',
  },
  {
    id: 'q105-06',
    topicId: '105',
    lessonId: '105.2',
    question: 'What does the special variable $# contain in a bash script?',
    options: ['The PID of the current shell', 'The name of the script', 'The number of positional arguments', 'The exit status of the last command'],
    correct: 2,
    explanation: '$# holds the count of positional arguments passed to the script or function. $0=script name, $1-$9=arguments, $@=all arguments as separate words.',
    difficulty: 'medium',
  },
  {
    id: 'q105-07',
    topicId: '105',
    lessonId: '105.3',
    question: 'Which SQL statement is used to retrieve data from a database table?',
    options: ['GET', 'FETCH', 'SELECT', 'RETRIEVE'],
    correct: 2,
    explanation: 'SELECT is the SQL DML statement for querying data. Basic syntax: SELECT columns FROM table WHERE condition ORDER BY column;',
    difficulty: 'easy',
  },
  {
    id: 'q105-08',
    topicId: '105',
    lessonId: '105.2',
    question: 'What is the purpose of the shebang line #!/bin/bash at the top of a script?',
    options: [
      'It is a comment that documents the script',
      'It tells the kernel to use /bin/bash as the interpreter for this script',
      'It sets bash as the default system shell',
      'It enables bash strict mode',
    ],
    correct: 1,
    explanation: 'The shebang (#!) followed by the interpreter path tells the OS which program to use when executing the script directly (e.g., ./myscript.sh).',
    difficulty: 'easy',
  },
  {
    id: 'q105-09',
    topicId: '105',
    lessonId: '105.2',
    question: 'Which command reads a line from stdin and stores it in variable NAME?',
    options: ['input NAME', 'scan NAME', 'get NAME', 'read NAME'],
    correct: 3,
    explanation: 'read NAME reads one line from stdin and assigns it to NAME. Use read -p "prompt: " NAME to display a prompt. read -s hides input (for passwords).',
    difficulty: 'easy',
  },
  {
    id: 'q105-10',
    topicId: '105',
    lessonId: '105.1',
    question: 'Which file sets environment variables for all users on every login shell?',
    options: ['~/.bashrc', '/etc/bash.bashrc', '/etc/environment', '/etc/profile'],
    correct: 3,
    explanation: '/etc/profile is sourced for all login shells system-wide. /etc/environment sets basic env vars without shell syntax. /etc/bash.bashrc applies to interactive non-login bash shells.',
    difficulty: 'medium',
  },

  // ============================================================
  // TOPIC 106
  // ============================================================
  {
    id: 'q106-01',
    topicId: '106',
    lessonId: '106.1',
    question: 'What does DISPLAY=:0 mean in the X Window System?',
    options: [
      'Connect to display 0 on a remote host',
      'Use the first display on the local machine via Unix socket',
      'Disable display output',
      'Use port 0 for X11',
    ],
    correct: 1,
    explanation: ':0 means the first X display on the localhost, accessed via a Unix socket. For remote access: hostname:0. :0.0 specifies display 0, screen 0.',
    difficulty: 'medium',
  },
  {
    id: 'q106-02',
    topicId: '106',
    lessonId: '106.1',
    question: 'Which command configures display resolution, refresh rate, and multi-monitor layout in X11?',
    options: ['xset', 'xdpyinfo', 'xrandr', 'xmodmap'],
    correct: 2,
    explanation: 'xrandr (X Resize and Rotate) configures outputs: resolution, rotation, orientation, and multi-monitor setups. xdpyinfo shows display info. xset controls preferences.',
    difficulty: 'easy',
  },
  {
    id: 'q106-03',
    topicId: '106',
    lessonId: '106.1',
    question: 'Which SSH option(s) enable running remote X11 applications on the local display?',
    options: ['ssh -X (untrusted)', 'ssh -Y (trusted)', 'Both -X and -Y (different trust levels)', 'ssh -G'],
    correct: 2,
    explanation: 'ssh -X enables untrusted X11 forwarding; ssh -Y enables trusted forwarding (grants more permissions). Both tunnel X11 from remote to local display.',
    difficulty: 'medium',
  },
  {
    id: 'q106-04',
    topicId: '106',
    lessonId: '106.1',
    question: 'What is the main Xorg server configuration file?',
    options: ['/etc/X11/Xorg.conf', '/etc/X11/xorg.conf', '/etc/xorg.conf', '/usr/share/X11/xorg.conf'],
    correct: 1,
    explanation: '/etc/X11/xorg.conf is the Xorg configuration file. Modern Xorg auto-detects hardware; this file only needs to exist for custom configuration.',
    difficulty: 'easy',
  },
  {
    id: 'q106-05',
    topicId: '106',
    lessonId: '106.2',
    question: 'What protocol does VNC use for remote desktop access?',
    options: ['RDP', 'RFB', 'SPICE', 'X2Go'],
    correct: 1,
    explanation: 'VNC uses the RFB (Remote Frame Buffer) protocol. RDP is Microsoft\'s Windows protocol. SPICE is used by KVM virtual machines.',
    difficulty: 'medium',
  },
  {
    id: 'q106-06',
    topicId: '106',
    lessonId: '106.2',
    question: 'Which display manager is the default for the GNOME desktop environment?',
    options: ['LightDM', 'SDDM', 'GDM', 'XDM'],
    correct: 2,
    explanation: 'GDM (GNOME Display Manager) is GNOMEs default. SDDM is KDE Plasmas default. LightDM is a lightweight cross-desktop option. XDM is the classic X Display Manager.',
    difficulty: 'easy',
  },
  {
    id: 'q106-07',
    topicId: '106',
    lessonId: '106.3',
    question: 'What accessibility feature allows keyboard shortcuts to be pressed sequentially instead of simultaneously?',
    options: ['Slow Keys', 'Bounce Keys', 'Sticky Keys', 'Toggle Keys'],
    correct: 2,
    explanation: 'Sticky Keys lets users press Ctrl+Alt+Del etc. one key at a time. Slow Keys add a delay before a keypress registers. Bounce Keys prevent rapid repeated keypresses.',
    difficulty: 'easy',
  },
  {
    id: 'q106-08',
    topicId: '106',
    lessonId: '106.3',
    question: 'Which Linux screen reader provides accessibility for blind and visually impaired users in GNOME?',
    options: ['Festival', 'Espeak', 'Orca', 'Brltty'],
    correct: 2,
    explanation: 'Orca is the GNOME screen reader providing speech synthesis and braille output via AT-SPI. Brltty supports braille terminals. Festival/Espeak are TTS engines.',
    difficulty: 'medium',
  },
  {
    id: 'q106-09',
    topicId: '106',
    lessonId: '106.1',
    question: 'What does the xhost command do?',
    options: [
      'Starts the X server',
      'Controls which hosts or users may connect to the X server',
      'Shows running X clients',
      'Configures X input devices',
    ],
    correct: 1,
    explanation: 'xhost manages X server access control. "xhost +hostname" grants access. "xhost -" re-enables access control. "xhost +" allows everyone (insecure).',
    difficulty: 'medium',
  },
  {
    id: 'q106-10',
    topicId: '106',
    lessonId: '106.2',
    question: 'What does XDMCP enable in a networked environment?',
    options: [
      'Compressed remote desktop sessions',
      'Remote X display login sessions managed by a display manager',
      'X11 forwarding over SSH tunnels',
      'Bluetooth input device pairing',
    ],
    correct: 1,
    explanation: 'XDMCP (X Display Manager Control Protocol) allows remote X terminals to request a graphical login session from an XDMCP-enabled display manager (GDM, LightDM) on a server.',
    difficulty: 'medium',
  },

  // ============================================================
  // TOPIC 107
  // ============================================================
  {
    id: 'q107-01',
    topicId: '107',
    lessonId: '107.1',
    question: 'Which command changes an existing user\'s primary group?',
    options: ['groupmod username', 'usermod -g groupname username', 'chgrp groupname username', 'useradd -g groupname username'],
    correct: 1,
    explanation: 'usermod -g groupname username changes the primary group. -G (uppercase) sets supplementary groups. -aG appends to supplementary groups without removing others.',
    difficulty: 'medium',
  },
  {
    id: 'q107-02',
    topicId: '107',
    lessonId: '107.1',
    question: 'Which file stores hashed user passwords on modern Linux systems?',
    options: ['/etc/passwd', '/etc/shadow', '/etc/group', '/etc/gshadow'],
    correct: 1,
    explanation: '/etc/shadow stores hashed passwords (readable only by root). /etc/passwd shows "x" where the password used to be. /etc/gshadow stores group passwords.',
    difficulty: 'easy',
  },
  {
    id: 'q107-03',
    topicId: '107',
    lessonId: '107.1',
    question: 'Which command displays password aging information for a specific user?',
    options: ['passwd -l username', 'usermod -l username', 'chage -l username', 'id username'],
    correct: 2,
    explanation: 'chage -l username lists password aging: last change, expiry date, minimum/maximum days, warning period. chage without -l interactively sets aging parameters.',
    difficulty: 'easy',
  },
  {
    id: 'q107-04',
    topicId: '107',
    lessonId: '107.1',
    question: 'What is the purpose of /etc/skel?',
    options: [
      'Contains skeleton scripts for system init',
      'Holds template files copied into new users\' home directories on creation',
      'Stores system skeleton configuration files',
      'Provides fallback files when /home is unavailable',
    ],
    correct: 1,
    explanation: '/etc/skel (skeleton) contains default files (.bashrc, .profile, etc.) automatically copied to a new user\'s home directory when useradd -m creates it.',
    difficulty: 'easy',
  },
  {
    id: 'q107-05',
    topicId: '107',
    lessonId: '107.2',
    question: 'In crontab format, what does the entry "0 2 * * 0" mean?',
    options: [
      'Every 2 minutes on Sundays',
      'At 2:00 AM every day',
      'At midnight every Sunday',
      'At 2:00 AM every Sunday',
    ],
    correct: 3,
    explanation: 'Crontab: min hour day month weekday. "0 2 * * 0" = minute 0, hour 2, any day, any month, weekday 0 (Sunday). Runs every Sunday at 2:00 AM.',
    difficulty: 'medium',
  },
  {
    id: 'q107-06',
    topicId: '107',
    lessonId: '107.2',
    question: 'Which command opens the current user\'s personal crontab for editing?',
    options: ['cron -e', 'crontab -e', 'vi /etc/crontab', 'edit-cron'],
    correct: 1,
    explanation: 'crontab -e opens the user\'s crontab in the default editor. crontab -l lists it, crontab -r removes it. /etc/crontab is the system-wide crontab for root/administrative jobs.',
    difficulty: 'easy',
  },
  {
    id: 'q107-07',
    topicId: '107',
    lessonId: '107.3',
    question: 'Which command displays all current locale settings for the shell session?',
    options: ['locale', 'localectl', 'setlocale', 'env | grep LANG'],
    correct: 0,
    explanation: 'locale (without args) displays all LC_* and LANG environment variables currently set. localectl shows/sets system-wide locale in systemd systems.',
    difficulty: 'easy',
  },
  {
    id: 'q107-08',
    topicId: '107',
    lessonId: '107.3',
    question: 'What is the effect of setting LC_ALL=C in a script?',
    options: [
      'Disables locale support entirely',
      'Forces POSIX/C locale overriding all other LC_* variables',
      'Sets locale to the current country',
      'Enables multi-byte character support',
    ],
    correct: 1,
    explanation: 'LC_ALL=C forces the POSIX "C" locale, overriding ALL other LC_* and LANG settings. Ensures consistent ASCII/byte-level behavior in scripts regardless of system locale.',
    difficulty: 'medium',
  },
  {
    id: 'q107-09',
    topicId: '107',
    lessonId: '107.1',
    question: 'How do you add user "alice" to the group "docker" without removing her from other groups?',
    options: [
      'usermod -g docker alice',
      'usermod -G docker alice',
      'usermod -aG docker alice',
      'groupadd alice docker',
    ],
    correct: 2,
    explanation: 'usermod -aG (append Group) adds the user to a supplementary group while keeping existing memberships. -G alone replaces ALL supplementary groups with only the listed one.',
    difficulty: 'easy',
  },
  {
    id: 'q107-10',
    topicId: '107',
    lessonId: '107.2',
    question: 'Which directory contains individual user crontab files managed by the cron daemon?',
    options: ['/etc/cron.d/', '/var/spool/cron/', '/etc/cron.daily/', '/tmp/crontabs/'],
    correct: 1,
    explanation: '/var/spool/cron/ (or /var/spool/cron/crontabs/) stores per-user crontab files named after the username. These are managed via crontab -e, not edited directly.',
    difficulty: 'hard',
  },

  // ============================================================
  // TOPIC 108
  // ============================================================
  {
    id: 'q108-01',
    topicId: '108',
    lessonId: '108.1',
    question: 'Which hwclock option writes the current system clock time to the hardware clock?',
    options: ['hwclock --hctosys', 'hwclock --systohc', 'hwclock --sync', 'hwclock --set'],
    correct: 1,
    explanation: 'hwclock --systohc (system to hardware clock) sets the hardware/BIOS clock to the current software time. --hctosys does the reverse (hardware to system).',
    difficulty: 'medium',
  },
  {
    id: 'q108-02',
    topicId: '108',
    lessonId: '108.1',
    question: 'Which systemd command displays and sets the system timezone?',
    options: ['tzconfig', 'tzselect', 'timedatectl', 'dpkg-reconfigure tzdata'],
    correct: 2,
    explanation: 'timedatectl is the systemd time management tool. "timedatectl set-timezone America/New_York" sets the timezone. "timedatectl list-timezones" shows available zones.',
    difficulty: 'easy',
  },
  {
    id: 'q108-03',
    topicId: '108',
    lessonId: '108.2',
    question: 'What does the logger command do?',
    options: [
      'Configures the syslog daemon',
      'Displays recent log entries from syslog',
      'Writes a message to the system log via syslog',
      'Creates a new log file',
    ],
    correct: 2,
    explanation: 'logger writes messages to the syslog facility from the shell. Example: logger -p user.info "Backup started" — useful in scripts to record events in system logs.',
    difficulty: 'easy',
  },
  {
    id: 'q108-04',
    topicId: '108',
    lessonId: '108.2',
    question: 'In rsyslog, which facility.severity selector captures all messages from all facilities at every level?',
    options: ['*.*', 'all.all', 'kern.*', '*.emerg'],
    correct: 0,
    explanation: '*.* matches all facilities and all severity levels. kern.* = only kernel at any level. *.emerg = all facilities at emergency level only.',
    difficulty: 'easy',
  },
  {
    id: 'q108-05',
    topicId: '108',
    lessonId: '108.2',
    question: 'What is the purpose of logrotate?',
    options: [
      'Encrypts log files for security',
      'Sends log files to a remote syslog server',
      'Automatically rotates, compresses, and removes old log files',
      'Formats log files into a structured database',
    ],
    correct: 2,
    explanation: 'logrotate manages log file growth by rotating (renaming), compressing (gzip), and deleting based on rules in /etc/logrotate.conf and /etc/logrotate.d/.',
    difficulty: 'easy',
  },
  {
    id: 'q108-06',
    topicId: '108',
    lessonId: '108.3',
    question: 'What is the role of an MTA (Mail Transfer Agent)?',
    options: [
      'Provides a mail client UI for users',
      'Stores mail in user mailboxes (final delivery)',
      'Routes and transfers email between mail servers using SMTP',
      'Filters spam from incoming messages',
    ],
    correct: 2,
    explanation: 'An MTA (e.g., Postfix, Sendmail, Exim) routes email between servers using SMTP. MUA=mail client, MDA=delivers to mailbox, MTA=transfers between servers.',
    difficulty: 'easy',
  },
  {
    id: 'q108-07',
    topicId: '108',
    lessonId: '108.3',
    question: 'What command-line program sends a simple email from the terminal?',
    options: ['sendmail -v user@host', 'mail -s "subject" user@host', 'smtp user@host', 'mutt --send user@host'],
    correct: 1,
    explanation: 'mail (or mailx) sends email from the command line. Usage: echo "body" | mail -s "Subject" user@example.com. Useful in scripts and cron jobs.',
    difficulty: 'medium',
  },
  {
    id: 'q108-08',
    topicId: '108',
    lessonId: '108.4',
    question: 'What is CUPS used for in Linux?',
    options: [
      'A text editor with clipboard support',
      'Managing printers and print jobs',
      'Compressed Unified Packet System for networking',
      'A container runtime',
    ],
    correct: 1,
    explanation: 'CUPS (Common Unix Printing System) manages printers and print jobs on Linux/macOS. Web interface at http://localhost:631. CLI tools: lp, lpstat, lpadmin, lpq.',
    difficulty: 'easy',
  },
  {
    id: 'q108-09',
    topicId: '108',
    lessonId: '108.4',
    question: 'Which command lists all available printers and their status in CUPS?',
    options: ['lp -l', 'lpq', 'lpstat -p', 'cupsctl --status'],
    correct: 2,
    explanation: 'lpstat -p lists all printers and their enabled/disabled status. lpstat -a shows acceptance status. lpq shows the default printer queue. lp submits print jobs.',
    difficulty: 'medium',
  },
  {
    id: 'q108-10',
    topicId: '108',
    lessonId: '108.1',
    question: 'Which NTP daemon is a modern, accurate alternative to ntpd suitable for intermittent connectivity?',
    options: ['timesyncd', 'chronyd', 'ntpdate', 'openntpd'],
    correct: 1,
    explanation: 'chronyd (chrony package) handles systems with intermittent network connectivity and variable clock drift better than ntpd. systemd-timesyncd is a simpler SNTP client built into systemd.',
    difficulty: 'medium',
  },

  // ============================================================
  // TOPIC 109
  // ============================================================
  {
    id: 'q109-01',
    topicId: '109',
    lessonId: '109.1',
    question: 'What is the subnet mask for a /24 CIDR network?',
    options: ['255.255.0.0', '255.255.255.0', '255.255.255.128', '255.0.0.0'],
    correct: 1,
    explanation: '/24 = 24 network bits, 8 host bits. Dotted decimal: 255.255.255.0. Provides 254 usable host addresses (256 − 2 for network and broadcast addresses).',
    difficulty: 'easy',
  },
  {
    id: 'q109-02',
    topicId: '109',
    lessonId: '109.1',
    question: 'Which TCP port does SSH use by default?',
    options: ['21', '22', '23', '443'],
    correct: 1,
    explanation: 'SSH uses TCP port 22. Port 21=FTP, 23=Telnet (insecure), 443=HTTPS. The default can be changed in /etc/ssh/sshd_config with the Port directive.',
    difficulty: 'easy',
  },
  {
    id: 'q109-03',
    topicId: '109',
    lessonId: '109.2',
    question: 'Which modern command replaces the deprecated ifconfig for managing network interfaces?',
    options: ['netconf', 'ifup', 'ip', 'nmcli'],
    correct: 2,
    explanation: 'The ip command (iproute2 package) replaces ifconfig, route, and arp. Examples: ip addr show, ip route show, ip link set eth0 up.',
    difficulty: 'easy',
  },
  {
    id: 'q109-04',
    topicId: '109',
    lessonId: '109.4',
    question: 'Which file configures DNS resolver settings (nameserver addresses) on Linux?',
    options: ['/etc/hosts', '/etc/nsswitch.conf', '/etc/resolv.conf', '/etc/named.conf'],
    correct: 2,
    explanation: '/etc/resolv.conf specifies DNS nameservers (nameserver 8.8.8.8) and search domains. /etc/nsswitch.conf controls lookup order. /etc/named.conf configures a local named server.',
    difficulty: 'easy',
  },
  {
    id: 'q109-05',
    topicId: '109',
    lessonId: '109.3',
    question: 'Which command is the modern replacement for netstat to display socket statistics?',
    options: ['ss', 'sockstat', 'nstat', 'ipcmd'],
    correct: 0,
    explanation: 'ss (socket statistics) replaces netstat. Common: ss -tuln (TCP/UDP listening, numeric). ss -tnp shows processes. ss is faster because it reads from kernel directly.',
    difficulty: 'medium',
  },
  {
    id: 'q109-06',
    topicId: '109',
    lessonId: '109.1',
    question: 'What is the purpose of ARP (Address Resolution Protocol)?',
    options: [
      'Assigns IP addresses dynamically to hosts',
      'Maps IP addresses to MAC (hardware) addresses on a LAN',
      'Resolves domain names to IP addresses',
      'Routes packets between networks',
    ],
    correct: 1,
    explanation: 'ARP resolves IPv4 addresses to MAC addresses on the same network segment. A device broadcasts "Who has IP x.x.x.x?" and the owner replies with its MAC address.',
    difficulty: 'easy',
  },
  {
    id: 'q109-07',
    topicId: '109',
    lessonId: '109.2',
    question: 'Which tool is the primary network configuration manager on modern desktop Linux?',
    options: ['wicd', 'ifupdown', 'NetworkManager', 'netplan'],
    correct: 2,
    explanation: 'NetworkManager is the default on most modern desktop distros. Controlled via nmcli (CLI), nmtui (text UI), or the desktop GUI. netplan is Ubuntu\'s frontend that generates NM/systemd-networkd config.',
    difficulty: 'easy',
  },
  {
    id: 'q109-08',
    topicId: '109',
    lessonId: '109.3',
    question: 'Which command efficiently tests if a specific TCP port is open on a remote host?',
    options: ['ping -p 80 host', 'traceroute -p 80 host', 'nmap -p 80 host', 'route -p 80 host'],
    correct: 2,
    explanation: 'nmap -p 80 host scans TCP port 80 on the target. ping uses ICMP (no port testing). traceroute shows path. telnet host port also verifies TCP connectivity.',
    difficulty: 'medium',
  },
  {
    id: 'q109-09',
    topicId: '109',
    lessonId: '109.1',
    question: 'Which IPv4 address class has a default subnet mask of 255.255.0.0?',
    options: ['Class A', 'Class B', 'Class C', 'Class D'],
    correct: 1,
    explanation: 'Class B (128.0.0.0–191.255.255.255) has default mask 255.255.0.0 (/16). Class A=/8 (255.0.0.0). Class C=/24 (255.255.255.0). Class D=multicast (no mask).',
    difficulty: 'medium',
  },
  {
    id: 'q109-10',
    topicId: '109',
    lessonId: '109.4',
    question: 'Which file provides static hostname-to-IP address mappings, checked before DNS?',
    options: ['/etc/hostname', '/etc/hosts', '/etc/resolv.conf', '/etc/networks'],
    correct: 1,
    explanation: '/etc/hosts provides static resolution, checked before DNS by default (configured in /etc/nsswitch.conf). Format: "192.168.1.10 server1 server1.local".',
    difficulty: 'easy',
  },

  // ============================================================
  // TOPIC 110
  // ============================================================
  {
    id: 'q110-01',
    topicId: '110',
    lessonId: '110.1',
    question: 'Which command shows recent successful user login history from the wtmp log?',
    options: ['w', 'who', 'last', 'lastb'],
    correct: 2,
    explanation: 'last reads /var/log/wtmp showing login history: user, TTY, remote host, and session times. lastb shows failed login attempts from /var/log/btmp.',
    difficulty: 'easy',
  },
  {
    id: 'q110-02',
    topicId: '110',
    lessonId: '110.1',
    question: 'Which find command locates all regular files with the SUID bit set?',
    options: [
      'ls -la / | grep s',
      'find / -perm -4000 -type f',
      'find / -suid -type f',
      'locate -perm +s',
    ],
    correct: 1,
    explanation: 'find / -perm -4000 -type f finds all regular files with the SUID bit. SUID files run with the owner\'s privileges — a common security audit check.',
    difficulty: 'medium',
  },
  {
    id: 'q110-03',
    topicId: '110',
    lessonId: '110.3',
    question: 'Which command generates a new SSH RSA key pair?',
    options: ['ssh-add -t rsa', 'ssh-copy-id -t rsa', 'ssh-keygen -t rsa', 'openssl genrsa'],
    correct: 2,
    explanation: 'ssh-keygen -t rsa generates RSA key pair. Private key → ~/.ssh/id_rsa, public key → ~/.ssh/id_rsa.pub. Use -b 4096 for stronger keys or -t ed25519 for modern curves.',
    difficulty: 'easy',
  },
  {
    id: 'q110-04',
    topicId: '110',
    lessonId: '110.3',
    question: 'Which file on the remote SSH server must hold the client\'s public key for passwordless login?',
    options: ['~/.ssh/id_rsa.pub', '~/.ssh/known_hosts', '~/.ssh/authorized_keys', '/etc/ssh/authorized_keys'],
    correct: 2,
    explanation: '~/.ssh/authorized_keys on the target server stores trusted public keys. Use ssh-copy-id user@host to automate copying. File permissions must be 600.',
    difficulty: 'easy',
  },
  {
    id: 'q110-05',
    topicId: '110',
    lessonId: '110.3',
    question: 'Which GPG command encrypts a file so only the specified recipient can decrypt it?',
    options: [
      'gpg --sign --recipient user@email file',
      'gpg --encrypt --recipient user@email file',
      'gpg --symmetric --recipient user@email file',
      'gpg --armor user@email file',
    ],
    correct: 1,
    explanation: 'gpg --encrypt --recipient user@email file encrypts using the recipient\'s public key. Only their private key can decrypt. --sign adds a digital signature.',
    difficulty: 'medium',
  },
  {
    id: 'q110-06',
    topicId: '110',
    lessonId: '110.1',
    question: 'Which file controls sudo privileges, and what tool must be used to edit it safely?',
    options: [
      '/etc/sudo — edited with sudoedit',
      '/etc/sudoers — edited with visudo',
      '/etc/sudo.conf — edited with nano',
      '/etc/security/sudoers — edited with sudoedit',
    ],
    correct: 1,
    explanation: '/etc/sudoers controls sudo access. ALWAYS use visudo to edit — it performs syntax checking before saving, preventing configuration errors that could lock you out.',
    difficulty: 'easy',
  },
  {
    id: 'q110-07',
    topicId: '110',
    lessonId: '110.2',
    question: 'What files does TCP Wrappers use to control access to network services?',
    options: [
      '/etc/network/allow and /etc/network/deny',
      '/etc/hosts.allow and /etc/hosts.deny',
      '/etc/tcp.allow and /etc/tcp.deny',
      '/etc/services.conf',
    ],
    correct: 1,
    explanation: 'TCP Wrappers (libwrap) uses /etc/hosts.allow (permitted) and /etc/hosts.deny (denied). hosts.allow is checked first; if matched, access is granted. Format: "daemon: host".',
    difficulty: 'medium',
  },
  {
    id: 'q110-08',
    topicId: '110',
    lessonId: '110.2',
    question: 'Which frameworks implement Mandatory Access Control (MAC) on Linux?',
    options: ['Only SELinux (RHEL/Fedora)', 'Only AppArmor (Ubuntu/SUSE)', 'Both SELinux and AppArmor', 'sudo and PAM'],
    correct: 2,
    explanation: 'Both SELinux (labels every object; used by RHEL/CentOS/Fedora) and AppArmor (path-based profiles; used by Ubuntu/SUSE) implement MAC on Linux.',
    difficulty: 'medium',
  },
  {
    id: 'q110-09',
    topicId: '110',
    lessonId: '110.1',
    question: 'Which iptables command appends a rule to accept incoming TCP connections on port 22?',
    options: [
      'iptables -I INPUT -p tcp --dport 22 -j ACCEPT',
      'iptables -A INPUT -p tcp --dport 22 -j ACCEPT',
      'iptables -A ACCEPT -p tcp --dport 22',
      'iptables --allow INPUT tcp 22',
    ],
    correct: 1,
    explanation: 'iptables -A INPUT appends to the INPUT chain. -p tcp = TCP protocol. --dport 22 = destination port 22. -j ACCEPT = accept the packet. -I inserts at the top of the chain.',
    difficulty: 'medium',
  },
  {
    id: 'q110-10',
    topicId: '110',
    lessonId: '110.2',
    question: 'What does "nmap -sV -p 1-1024 192.168.1.1" do?',
    options: [
      'Scans for open UDP ports only',
      'Performs a stealth SYN scan on all ports',
      'Scans TCP ports 1–1024 and attempts to detect service versions',
      'Scans all 65535 ports silently',
    ],
    correct: 2,
    explanation: 'nmap -sV (version detection) -p 1-1024 (port range) scans ports 1 to 1024 and identifies service names/versions. Essential for security auditing and inventory.',
    difficulty: 'medium',
  },
]

// Get questions for a specific topic
export function getQuizByTopic(topicId: string): QuizQuestion[] {
  return quizQuestions.filter((q) => q.topicId === topicId)
}

// Get all questions for full exam (shuffled)
export function getAllQuestions(): QuizQuestion[] {
  return [...quizQuestions].sort(() => Math.random() - 0.5)
}
